SwifterSwift/SwifterSwift

SwifterSwift/SwifterSwift/Extensions/StringExtensions.swift

Added new extension for String to convert to Date based on entered format. Refer below for example use
```swift
let dateString = "2016/10/20"
let format = "yyyy/MM/dd"
let date = dateString.toDate(withFormat: format)
print("The date is ---- \(date)")
```

new String extension added

---

SwifterSwift/SwifterSwift/Extensions/ArrayExtensions.swift

Reduce can be used for remove duplicates in array rather than use of for loop in array. 
Thanks for the beautiful extensions.

use of reduce for remove duplicates in array

---

README.md

Colon missing for date methods beginning and end.

Colon missing in date extension in readme.md

---

Source/Extensions/ArrayExtensions.swift
Source/Extensions/CollectionExtensions.swift

safe way to access array index elements no worry of out of bounds

---

Source/Extensions/UI/UIColorExtensions.swift

This basically extends UIColor allowing to get the complementary of any given color by using the `getComplementary(forColor: UIColor) -> UIColor` static method or the `complementary` property.
Here's a `.playground` screenshot of a working example:
> The color complementation algorithm uses non-linearity (*γ-correction*) of `sRGB` color space to derive a better formula for inverting a color channel in order to obtain a visually better complementary color.
BTW thanks for the great project 😄

feat: allow to get complementary of any given color

---

SwifterSwift.xcodeproj/project.pbxproj

Hello. Looks like the location of info.plist for tests target was incorrect and I couldn't run the test suite locally. This change fixes it.

fix info life location for tests target

---

Source/Extensions/StringExtensions.swift
Tests/SwifterSwiftTests/StringExtensionsTests.swift

Hello. I am a Ruby developer playing around with Swift for a while now. One of the things I keep missing is **String#slice** method from Ruby stdlib. This is implementation that replicates the behaviour of a Ruby **String#slice** for integer argument types https://ruby-doc.org/core-2.2.0/String.html#method-i-slice . Kind of bombarded it with tests but wanted to cover all the edge cases. Hope that can be useful.

Add String slice method and tests

---

.travis.yml
Source/Extensions/StringExtensions.swift
Source/Extensions/SwifterSwift.swift
Source/Extensions/UI/NSAttributedStringExtensions.swift
SwifterSwift.podspec
SwifterSwift.xcodeproj/project.pbxproj
SwifterSwift.xcodeproj/xcshareddata/xcschemes/SwifterSwift iOS.xcscheme
SwifterSwift.xcodeproj/xcshareddata/xcschemes/SwifterSwift tvOS.xcscheme
Tests/SwifterSwiftTests/CGFloatExtensionsTests.swift

Hello. It is an initial version of adding tvOS target. I copied how targets for multiple platforms are added in https://github.com/Alamofire/Alamofire . For now I added macros for code that was failing on tvOS just to have an initial version working. Looking forward to your opinion on that. Maybe a cleaner approach would be to split platform specific extensions into seperate files and do not even include them in noncompatible targets.

[#56] initial tvOS setup

---

SwifterSwift.podspec
SwifterSwift.xcodeproj/project.pbxproj
SwifterSwift.xcodeproj/xcshareddata/xcschemes/SwifterSwift watchOS.xcscheme

Looks like currently there is no way to test watchOS targets. What is recommended is to test the code in iOS target what we already do. I just did not include files with code not compatible with watchOS into the target.
I tested it with Carthage and imported into a dummy watchOS app. I managed to import framework module but looks like types are not extended because I cannot use any of the SwifterSwift methods. Could you take a look at it? Maybe some lib linking setting that I forgot to tick or sth.

[#81] add watchOS target

---

.travis.yml

Should be fine now. I removed xcpretty because I think that it breaks the return value of test script and could cause false positive build statuses.

Add travis support for all the targets

---

Tests/SwifterSwiftTests/SwifterSwiftTests.swift

Two specs I recently added were notably slower then rest of the suite. With decreased delays they work the same but faster.

decrease time delays for async specs

---

Source/Extensions/StringExtensions.swift
Tests/SwifterSwiftTests/StringExtensionsTests.swift

Added isValidUrl property to StringExtensions.

Added isValidUrl to StringExtensions

---

Source/Extensions/StringExtensions.swift
Tests/SwifterSwiftTests/StringExtensionsTests.swift

Added isValidSchemedUrl property to StringExtensions.

Added isValidSchemedUrl to StringExtensions

---

Source/Extensions/SwifterSwift.swift

Hello. I applied a little improvement to delay function. It returns a cancellable DispatchWorkItem instance now.

allow delayed execution to be cancelled

---

Source/Extensions/UIKit/UICollectionViewExtensions.swift
Source/Extensions/UIKit/UIStoryboardExtensions.swift
Source/Extensions/UIKit/UITableViewExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj

- [  ] I have added tests for new extensions, and they passed.
Pull request summary:
Affects 2 existing classes: UITableView, UICollectionView
- The methods added to these classes allow a user to both deque and register cells using the class name as the identifier as opposed to the traditional String.
Adds 1 new class: UIStoryboard
- A new method was added allowing the user to instantiate a UIViewController using its class name as the identifier.
I have not written Unit Tests for these methods.

Add Class identifier methods

---

Source/Extensions/Cocoa/CGAffineTransformExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwifterSwiftTests/CocoaExtensionsTests/CGAffineTransformExtensionsTests.swift

First of all sorry for submitting duplicate requests. I broke something major and had to re-fork.
- Adds files for CGAffineTransform extensions + tests

Add CGAffineTransformExtensions: subtracting(transform:)

---

Source/Extensions/Cocoa/CGFloatExtensions.swift
Source/Extensions/DoubleExtensions.swift
Source/Extensions/FloatExtensions.swift
Source/Extensions/IntExtensions.swift
Source/Extensions/UIKit/UIViewExtensions.swift
Tests/SwifterSwiftTests/CocoaExtensionsTests/CGFloatExtensionsTests.swift
Tests/SwifterSwiftTests/DoubleExtensionsTests.swift
Tests/SwifterSwiftTests/FloatExtensionsTests.swift
Tests/SwifterSwiftTests/IntExtensionsTests.swift

`M_PI` is deprecated in Swift 3.1 (Xcode 8.3 beta 2). 
This pull request replaces all `M_PI` with `Double.pi` or `.pi` of corresponding types in the context.

Replace deprecated 'M_PI' with '.pi'

---

SwifterSwift.xcodeproj/project.pbxproj
Tests/SwifterSwiftTests/UIKitExtensionsTests/UIAlertControllerExtensionsTests.swift

- This PR adds no new extensions
- Adds new test file for UIAlertControllerExtensions
- The only method not tested is the show(animated:vibrate:completion:)
I had a lot of difficulty figuring out how to test if the controller was actually presented considering there is no UIApplicationMain.

Add UIAlertControllerExtensionsTests

---

SwifterSwift.xcodeproj/project.pbxproj
Tests/SwifterSwiftTests/UIKitExtensionsTests/UIBarButtonExtensionsTests.swift
Tests/SwifterSwiftTests/UIKitExtensionsTests/UIButtonExtensionsTests.swift

- This PR adds no new extensions
- Adds 2 new files for testing UIBarButtonItem + UIButton extensions
- All methods/properties are tested
Not related to Pull Request:
Consider the following method name change for UIBarButtonItem:
From:
``` func addTargetForAction(target: AnyObject, action: Selector)```
To:
```func add(target: AnyObject, for action: Selector)```

Add UIBarButtonItem+UIButtonExtensions tests

---

Source/Extensions/UIKit/UISegmentedControlExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwifterSwiftTests/UIKitExtensionsTests/UISegmentedControlExtensionsTests.swift
Tests/SwifterSwiftTests/UIKitExtensionsTests/UITextFieldExtensionsTests.swift

- Updates implementation of UISegmentedControl extensions to return array of non-optionals
- This has been discussed in issue #120
- Adds complete testing for UISegmentedControlExtensions
- Adds a single test for UITextFieldExtensions
```setPlaceHolderTextColor```
I'm working on a bigger PR with more UIKit testing at the moment. Lots of things holding me up today.

Add UITextView+UISegmentedControl tests #120

---

SwifterSwift.xcodeproj/project.pbxproj
Tests/SwifterSwiftTests/UIKitExtensionsTests/UINavigationBarExtensionTests.swift
Tests/SwifterSwiftTests/UIKitExtensionsTests/UINavigationControllerExtensionsTests.swift
Tests/SwifterSwiftTests/UIKitExtensionsTests/UINavigationItemExtensionsTests.swift
Tests/SwifterSwiftTests/UIKitExtensionsTests/UISliderExtensionsTests.swift

- Completely test UINavigationBarExtensions
- Completely test UINavigationControllerExtensions
- Completely test UINavigationItemExtensions
- Completely test UISliderExtensions

Add UINavigationElements+UISlider tests

---

Source/Extensions/UIKit/UIImageViewExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwifterSwiftTests/UIKitExtensionsTests/UIImageViewExtensionsTests.swift

- Adds complete testing for UIImageViewExtensions
- Fixes endless recursive call in blurred() method
Something we may want to consider here is combining the blur() and blurred() methods and just giving it a discardable result. I didn't implement this since I was not the one who originally created the extension.
- Note for the blur() method I did not like that I could not test if the applied UIVisualEffectView has the …

Add UIImageViewExtensionsTests + Fix infinite recursive call

---

SwifterSwift.xcodeproj/project.pbxproj
Tests/SwifterSwiftTests/UIKitExtensionsTests/TestStoryboard.storyboard
Tests/SwifterSwiftTests/UIKitExtensionsTests/UIStoryboardExtensionsTests.swift
Tests/SwifterSwiftTests/UIKitExtensionsTests/UIViewControllerExtensionsTests.swift

- Adds complete testing for UIViewControllerExtensions & UIStoryboardExtensions
- Added a new file TestStoryboard to the SwifterSwiftTests target

Add UIViewController+UIStoryboardExtensions tests

---

Source/Extensions/ArrayExtensions.swift
Tests/SwifterSwiftTests/ArrayExtensionsTests.swift

@omaralbeik don't merge this yet it's in progress
- Updated `shuffle()` / `shuffled()` methods to use Fisher-Yates Algorithm
Replaces the previous **O(n^2)** complexity with **O(n)**
The output is now completely random. I've removed the check against the original array.
- Converted `shuffled` and `withoutDuplicates` properties to methods
`withoutDuplicates` has been renamed to `duplicatesRemoved()`
- Updating `pop()` to just return the result of `popLast()` so we can rely on the standard libraries implementation of this method
I'm considering putting the shuffle() / shuffled() methods on an extension to MutableCollection
This way they will work for not only Arrays but ArraySlices as well.
This can be refactored at a later date.
The main reason I'm holding off on this is because having an …

Reduce shuffle()/shuffled() complexity and minor updates

---

Source/Extensions/UIKit/UIViewExtensions.swift

Add quick setter and getter for `x` and `y` to UIView extension

---

Source/Extensions/ArrayExtensions.swift
Source/Extensions/CollectionExtensions.swift
Source/Extensions/UIKit/UICollectionViewExtensions.swift
Tests/SwifterSwiftTests/ArrayExtensionsTests.swift

- Convert remaining O(N) Array properties to methods.
- Simplified `firstIndex(of:)` and `lastIndex(of:)` methods by moving them into a conditional extension.
This removed the messy generic constraint on the parameter and now prohibits the caller from passing from passing in a different type than the elements of the array. Thus, also removes some unsafe casting.
- ~~Added the `average()` method back to `Array` for `Integer` elements.
(with forced cast, haven't figured out how to avoid this yet)~~
I didn't see this got moved to an extension on Collection so I removed my change.
I did convert this to a method though.
EDIT: Considering moving this back to Array so we can get the average of `Int` or `UInt` arrays.
- Updated all ranges based on `0..<count` logic to use …

Refactor Array properties to  methods and minor simplifications

---

Source/Extensions/ArrayExtensions.swift
Tests/SwifterSwiftTests/ArrayExtensionsTests.swift

New **Array** Extensions
- `func firstIndex(where condition: (Element) -> Bool) -> Int?`
- `func lastIndex(where condition: (Element) -> Bool) -> Int?`
- `func last(where condition: (Element) -> Bool) -> Element?`
- `func indices(where conditon: (Element) -> Bool) -> [Int]?`
- `func reject(where condition: (Element) -> Bool) -> [Element]`
- `func all(match condition: (Element) -> Bool) -> Bool`
- `func none(match condition: (Element) -> Bool) -> Bool`
- `func count(where condition: (Element) -> Bool) -> Int`
- `func forEachReversed(body: (Element) -> Void)`
- `func accumulate<U>(initial: U, next: (U, Element) -> U) -> [U]`

Add new Array extensions

---

Source/Extensions/StringExtensions.swift
Tests/SwifterSwiftTests/StringExtensionsTests.swift

String matches regex extension and simplify isEmail implementation.

---

Source/Extensions/DateExtensions.swift
Source/Extensions/LocaleExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwifterSwiftTests/LocaleExtensionsTests.swift

Provides a static property for POSIX locale. Great on performance too since statically cached for reuse. Added new locale unit tests.
Instead of this:
```
dateFormatter.locale = Locale(identifier: "en_US_POSIX")
```
Do this:
```
dateFormatter.locale = .posix
```

Add new locale extension with POSIX static property

---

Source/Extensions/Cocoa/CLLocationExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwifterSwiftTests/CocoaExtensionsTests/CLLocationExtensionsTests.swift

CLLocationExtensions new file with extensions for midPoint and bearing between points.

---

Source/Extensions/ArrayExtensions.swift

ArrayExtensions has code coverage issue where **last** method code coverage report says **return nil** is not executed even though all the test passes. The exact reason for why this is happening is not clear.
But we have a similar method like **lastIndex** in same extensions which is returning nil. Here code coverage report says return nil executed. The only difference I see is the use of where condition in with for loop between lastIndex and last method. 
By this pull request, I made **last** method code similar as **lastIndex**.

ArrayExtensions last method codecoverage fix

---

Tests/SwifterSwiftTests/ArrayExtensionsTests.swift

Test case for an empty array is not covered as part of ArrayExtensions skip method test.
See below test coverage report for the same method.
This pull request adds the required empty array test case.

Added empty array test for ArrayExtension skip method

---

Tests/SwifterSwiftTests/ArrayExtensionsTests.swift

By this pull request, I am trying to add empty array test for both **drop** and **take** methods in 
ArrayExtenstions. By adding this, it is expected to have 100% test coverage for ArrayExtensions.swift file alone.

Adding empty array test case for drop and take methods

---

Source/Extensions/ArrayExtensions.swift
Tests/SwifterSwiftTests/ArrayExtensionsTests.swift

- Removes `drop(while:)` extension on `Array` that already exists in the Swift Standard Library

Remove drop(while:) Array extension

---

Source/Extensions/UIKit/UITextFieldExtensions.swift
Tests/SwifterSwiftTests/UIKitExtensionsTests/UIImageViewExtensionsTests.swift
Tests/SwifterSwiftTests/UIKitExtensionsTests/UITextFieldExtensionsTests.swift

- [😅] I checked the [**Contributing Guidelines**](https://github.com/omaralbeik/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [:+1:] I have **only one commit** in this pull request.
- [:+1: ] New extensions support iOS 8 or later.
- [:+1: ] New extensions are written in Swift 3.
- [:+1: ] I have added tests for new extensions, and they passed.
- [:+1:] Pull request was created to [**master head branch**](https://github.com/omaralbeik/SwifterSwift/tree/master).
- [:+1:] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [:+1:] All comments headers have the word **SwifterSwift:** before description.
- Adds new extension `addPaddingLeft(padding:)` for `UITextField`
- Hopefully fixes that pesky …

Add addPaddingLeft UITextField extension & fix broken UIImageView test

---

Source/Extensions/DictionaryExtensions.swift
Tests/SwifterSwiftTests/DictionaryExtensionsTests.swift

New dictionary extensions.

---

CHANGELOG.md
Sources/Extensions/Foundation/ArrayExtensions.swift
Tests/FoundationTests/ArrayExtensionsTests.swift

Adding array split(size:) method

---

CHANGELOG.md
Sources/Extensions/Foundation/ArrayExtensions.swift
Tests/FoundationTests/ArrayExtensionsTests.swift

Add rotated(by places: Int) and rotate(by places: Int) new array extensions.

---

.codecov.yml
Sources/Extensions/Cocoa/NSColorExtensions.swift
Sources/Extensions/UIKit/UIColorExtensions.swift
Sources/Extensions/UIKit/UIImageExtensions.swift
Tests/UIKitTests/UIColorExtensionsTests.swift
Tests/UIKitTests/UIImageExtensionsTests.swift

UIColor: HBSA component access, UInt conversion, access to CoreImage.CIColor, and FlatUI colors
NSColor: FlatUI colors
UIImage: Tinted image

UIColor, NSColor, and UIImage extensions

---

Sources/Extensions/UIKit/UIColorExtensions.swift
Tests/UIKitTests/UIColorExtensionsTests.swift

This PR addresses issue #214 
Issue: CoreImage is not available on watchOS, resulting in a compilation error. 
Fix: Restricts the accessor to be only available on iOS and tvOS via wrapping it in a conditional compilation block.

Fixed the CoreImage accessor in UIColor to be restricted to iOS and tvOS

---

CHANGELOG.md
Sources/Extensions/Cocoa/NSAttributedStringExtensions.swift
Sources/Extensions/Foundation/ArrayExtensions.swift
Sources/Extensions/Foundation/StringExtensions.swift
Tests/CocoaTests/NSAttributedStringExtensionsTests.swift

Adding missing string and array exemples.

New attributed string operators.

---

Sources/Extensions/Foundation/ArrayExtensions.swift

Sometimes the smallest code isn't always the most performant. I reckon `removeDuplicates()` and `duplicatesRemoved()` would also benefit from this approach. I was a bit too lazy though 😅
I'm using Travis to run my tests for this because my simulator was too slow 😐

Improve sum & average extensions by not relying on reduce

---

README.md
Sources/Extensions/Foundation/DoubleExtensions.swift
Sources/Extensions/Foundation/FloatExtensions.swift
Sources/Extensions/Foundation/FloatingPointExtensions.swift
Sources/Extensions/Foundation/IntExtensions.swift
Sources/Extensions/Foundation/SignedIntegerExtensions.swift
Sources/Extensions/Foundation/SignedNumberExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj

Add SignedNumberExtensions
Add SignedIntegerExtensions

Fixes #224

---

Sources/Extensions/UIKit/Deprecated/UIKitDeprecated.swift
Sources/Extensions/UIKit/UIColorExtensions.swift
Tests/UIKitTests/UIColorExtensionsTests.swift

also without `continue` @omaralbeik ;)
also little question here:
shouldn't `UIColor(hex: 0xABC)` generate `0xAABBCC` rather than `0x000ABC` ?

UIColor.hexString alpha support #190

---

CHANGELOG.md
Sources/Extensions/Foundation/DateExtensions.swift
Tests/FoundationTests/DateExtensionsTests.swift

Added a `isBetween` method to the date extension which can be used to determine if a date is between two given dates including or excluding the given dates itself. Default is to include the dates itself.

Add isBetween method to date extension

---

Sources/Extensions/UIKit/UILabelExtensions.swift
Tests/UIKitTests/UILabelExtensionsTests.swift

Add convenience initializer init(text:) to UILabel, including a test

---

Sources/Extensions/SwiftStdlib/BoolExtensions.swift
Tests/SwiftStdlibTests/BoolExtensionsTests.swift

I'm not quite sure about the test, but the chance that it fails should be sufficiently small.

Add random to Bool, including a test

---

Sources/Extensions/SwiftStdlib/StringExtensions.swift

I wasn't able to write tests for these extensions, because they require running with a different localization. As far as I know, it is currently not possible to set the 'Application Language' for a single test.

Add localized and localized(comment:) to String

---

SwifterSwift.xcodeproj/project.pbxproj
Tests/CoreGraphicsTests/CGColorExtensionsTests.swift

Only added tests to existing extensions, so many items in the checklist don't apply.

Added CGColorExtensionsTests for iOS and macOS

---

CHANGELOG.md
Sources/Extensions/Foundation/DataExtensions.swift
Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
SwifterSwift.xcodeproj/xcshareddata/xcschemes/SwifterSwift-iOS.xcscheme
SwifterSwift.xcodeproj/xcshareddata/xcschemes/SwifterSwift-macOS.xcscheme
SwifterSwift.xcodeproj/xcshareddata/xcschemes/SwifterSwift-tvOS.xcscheme
SwifterSwift.xcodeproj/xcshareddata/xcschemes/SwifterSwift-watchOS.xcscheme
Tests/FoundationTests/DataExtensionsTests.swift
Tests/SwiftStdlibTests/SignedNumericExtensionsTests.swift

300% speed improvement.
```swift
import Foundation
extension Array where Element: Numeric {
func sum() -> Element {
var total: Element = 0
forEach { total += $0 }
return total
}
func sumReduce() -> Element {
return self.reduce(0 as Element, +)
}
}
let ar = Array(0..<100_000)
var startTime = CFAbsoluteTimeGetCurrent()
print("sum()")
print("  = \(ar.sum())")
print("  in \(CFAbsoluteTimeGetCurrent() - startTime)s")
print("")
startTime = CFAbsoluteTimeGetCurrent()
print("sumReduce()")
print("  = \(ar.sumReduce())")
print("  in \(CFAbsoluteTimeGetCurrent() - startTime)s")
```
Which would  result in:
```
sum()
= 4999950000
in 6.78056800365448s
sumReduce()
= 4999950000
in 0.0268669724464417s
```

Improve Array.sum() and Array.average()

---

Sources/Extensions/SwiftStdlib/ArrayExtensions.swift

- [x ] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.

add semicolons to lastIndex(of:) and firstIndex(of:) doc

---

Tests/FoundationTests/DateExtensionsTests.swift

Added a missing test for Date.isBetween extension method

Add test for Date.isBetween

---

Sources/Extensions/Foundation/DateExtensions.swift
Tests/FoundationTests/DateExtensionsTests.swift

Closes #258 Add isWithin extension to Date

---

Sources/Extensions/SwiftStdlib/OptionalExtensions.swift
Tests/SwiftStdlibTests/OptionalExtensionsTests.swift

add optional assignment operator: if `rhs` is not `nil`, assign it to `lhs`.

add optional assignment operator

---

Sources/Extensions/Foundation/DataExtensions.swift
Sources/Extensions/Foundation/DateExtensions.swift
Sources/Extensions/Shared/ColorExtensions.swift
Sources/Extensions/SwiftStdlib/IntExtensions.swift
Sources/Extensions/SwiftStdlib/StringExtensions.swift
Sources/Extensions/UIKit/UITabBarExtensions.swift
Sources/Extensions/UIKit/UIViewExtensions.swift
Tests/SharedTests/ColorExtensionsTests.swift

If I understood #294 correctly, then this should take care of cross-file references at least. I'm not sure of the issue with #286 since none of my findings include any UIKit extension references in the Foundation/Swift extension groups.
What this does _not_ do, currently, is intra-file references to other extensions since this is a difficult one to automate (see below). Specifically, I'm wondering if examples like in [NSAttributedString](https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/Extensions/Foundation/NSAttributedStringExtensions.swift#L51) would need to be refactored (since extensions like `.bolded` use the helper method `applying`)? Or if just examples like [NSURL](https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/Extensions/Foundation/URLExtensions.s …

Remove cross references #294

---

CHANGELOG.md
Sources/Extensions/AppKit/NSImageExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/AppKitTests/NSImageExtensionsTests.swift

Add a function to NSImage to be able to scale an image to some maximum size. It could be useful for creating thumbnails.

Add scaled(toMaxSize:NSSize) to NSImage, including a test

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

Adding padStart/padEnd and byPaddingStart/byPaddingEnd String extensions

---

Sources/Extensions/Foundation/DateExtensions.swift
Sources/Extensions/Foundation/Deprecated/FoundationDeprecated.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/FoundationTests/CalendarExtensionTest.swift
Tests/FoundationTests/DateExtensionsTests.swift

- Fixed a bug in `year` where setting year was resetting all smaller components to zero.
- Fixed a bug in `month` where setting month was resetting all smaller components to zero.
- Fixed a bug in `day` where setting day was resetting all smaller components to zero.
- Fixed a bug in `hour` where setting hour was resetting all smaller components to zero.
- Fixed a bug in `minute` where setting minute was resetting all smaller components to zero.
- Fixed a bug in `second` where setting second was resetting all smaller components to zero.
- Added validation to setters for properties above.
- Fixed the above bugs in `changing` method as well.
- Fixed a bug where `quarter` was returning 1 always.
- `weekday` is now get-only property.
- `isInThisWeek` has been renamed to `isInCurrentWeek`.
- …

Rewrite DateExtensions.swift

---

Sources/Extensions/Foundation/DateExtensions.swift
Tests/FoundationTests/DateExtensionsTests.swift

As per [this wikipedia page](https://en.wikipedia.org/wiki/Workweek_and_weekend)
Another variant is `isAWorkday` or `isAWeekday`, but I think `isInWorkweek` works better with `isInWeekend`

Rename weekday to workweek

---

CHANGELOG.md
Sources/Extensions/AppKit/NSImageExtensions.swift

Add `write(to url: URL, fileType type: _, compressionFactor: _)` method to write NSImage to url.

Add write() method to NSImage extensions

---

CHANGELOG.md
Sources/Extensions/Shared/ColorExtensions.swift
Tests/SharedTests/ColorExtensionsTests.swift

#324: Added Color extension methods to lighten and darken colors

Add lighten and darken methods to Color extension

---

Sources/Extensions/SwiftStdlib/ArrayExtensions.swift

Removing shuffle and shuffled equatable Element constraint.

---

CHANGELOG.md
Sources/Extensions/Foundation/DateExtensions.swift
Tests/FoundationTests/DateExtensionsTests.swift

Add dateString(withFormat:) to DateExtensions

---

CHANGELOG.md
Sources/Extensions/Foundation/DateExtensions.swift
Tests/FoundationTests/DateExtensionsTests.swift

Add random  extensions to Date #326

Add random and randomBetween extensions to Date #326

---

CHANGELOG.md
Sources/Extensions/Foundation/NSAttributedStringExtensions.swift
Tests/FoundationTests/NSAttributedStringExtensionsTests.swift

This property gets the attributes of a simple NSAttributedString. It works by checking the attributes from the first character and assuming that applies for the rest of the string. Let me know if you'd take another approach.

Attributes getter for NSAttributedString Issue #333

---

Sources/Extensions/UIKit/UINavigationBarExtensions.swift

**Fixed a bug where makeTransparent was keeping the background color**

Fixed makeTransparent background color

---

Sources/Extensions/Foundation/DateExtensions.swift
Tests/FoundationTests/DateExtensionsTests.swift

Added Date() extension - initiazlier using Ineger literal. Provides Date init from Int like 20171225, or 2017_12_25
* New extension added to DateExtensions.swift
* Test added to DateExtensionsTests.swift
- [] All extensions are declared as **public**.

Date extensions

---

Tests/FoundationTests/DateExtensionsTests.swift

I fixed issue in DateExtensionsTests.swift.
There're hardcoded values for date.add() method. I updated to actual values - 2017 (year-1), 2018 (current year)

DateExtensionsTests.swift fixed. currentYear - 1 is 2017 since today.

---

CHANGELOG.md
Sources/Extensions/Foundation/NSAttributedStringExtensions.swift
Tests/FoundationTests/NSAttributedStringExtensionsTests.swift

These methods apply attributes to regex patterns or substrings. They can be used to highlight emails/websites, names, etc...

Applying attributes to regex patterns and substrings

---

Sources/Extensions/Foundation/NSPredicateExtensions.swift
Tests/FoundationTests/NSPredicateExtensionsTests.swift

support
!NSPredicate(format: "SELF BETWEEN{1,5}")
NSPredicate(format: "SELF BETWEEN{1,5}") + NSPredicate(format: "SELF BETWEEN{3,6}")
NSPredicate(format: "SELF BETWEEN{1,5}") - NSPredicate(format: "SELF BETWEEN{3,6}")
NSPredicate(format: "SELF BETWEEN{1,5}") ^ NSPredicate(format: "SELF BETWEEN{3,6}")

operators for NSPredicate

---

CHANGELOG.md
Examples/Examples.md
Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
Sources/Extensions/SwiftStdlib/Deprecated/SwiftStdlibDeprecated.swift
Tests/SwiftStdlibTests/ArrayExtensionsTests.swift

Renamed method of `ArrayExtensions` `indexes(of:)` to `indices(of:)` since Apple's API is using that naming. There are few other usages in SwifterSwift project where _"indices"_ is used and this was only place where _"indexes"_ was used.

Renamed indexes(of:) to indices(of:) in ArrayExtension

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

Blank string check methods added in String extension

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
Tests/SwiftStdlibTests/ArrayExtensionsTests.swift

Added stablePartition by condition array method

---

Tests/FoundationTests/URLExtensionsTests.swift

As far as I know these overrides are unnecessary the tests finish as expected.

remove empty overrides in URLExtensionTests.swift

---

CHANGELOG.md
Sources/Extensions/Foundation/URLExtensions.swift
Sources/Extensions/UIKit/UIStoryboardExtensions.swift
Tests/FoundationTests/URLExtensionsTests.swift

This is useful for iMessage app/extensions because information is exchanged through URL query items but it might be useful in general.

Query parameters getter for URL

---

CHANGELOG.md
Sources/Extensions/UIKit/UIFontExtensions.swift
Tests/UIKitTests/UIFontExtensionsTest.swift

Add bold and italic properties to UIFont

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/StringProtocolExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwiftStdlibTests/StringProtocolExtensionsTests.swift

commonPrefix(with:, options:) is already in the standard library, commonSuffix(with:, options:) is not.

Add commonSuffix(with:, options:) to StringProtocol

---

CHANGELOG.md
Sources/Extensions/UIKit/UIImageExtensions.swift
Tests/UIKitTests/UIImageExtensionsTests.swift

Add withRoundedCorners(radius:) extension to UIImage

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/IntExtensions.swift
Sources/Extensions/SwiftStdlib/SignedIntegerExtensions.swift
Tests/SwiftStdlibTests/IntExtensionsTests.swift

This way of getting a number's digits is more performant and memory efficient, since we're not creating a new string and performing type castings.
Current version:
```swift
let intsArray = description.flatMap({Int(String($0))})		
return intsArray.map({Self($0)})
```

Refactors Int digits method for more performance

---

CHANGELOG.md
Sources/Extensions/Foundation/UserDefaultsExtensions.swift
Tests/FoundationTests/UserDefaultsExtensionsTests.swift

UserDefaults extension to save codable object

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

update isNumeric to check if string is a valid Swift number and add isDigits to check if string only contains digits

Fix for StringExtensions - isNumeric - incorrect behavior

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

Creates a method to return a slug version of a string.
Example:
```swift
let str = "  A nice & hög _ Str    "
str.toSlug() // Returns "a-nice-&-hog-str"
```

String to slug

---

CHANGELOG.md
Sources/Extensions/UIKit/UIStackViewExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/UIKitTests/UIStackViewExtensionsTest.swift

Adding a convenience init to UIStackView  to create a UIStackView from an Array of UIViews. Taking the defaults and parameter docs from Apples Defaults.
See also #407 
Closes #399

Add UIStackView convenience init with UIViews and parameters

---

Sources/Extensions/Shared/ColorExtensions.swift

Renamed NSColor and UIColor to Color
Resolves #412

Fix Issue #412: Rename NSColor to Color in ColorExtensions.swift

---

CHANGELOG.md
Sources/Extensions/MapKit/MKPolylineExtensions.swift
SwifterSwift.podspec
SwifterSwift.xcodeproj/project.pbxproj
Tests/MapKitTests/MKPolylineTests.swift

This PR adds the following two additions:
- A `.coordinate` property on an instance of `MKPolyline`, to return a list of coordinates from a provided `MKPolyline`.
- A `init(coordinates:)` initializer, to initialize a new `MKPolyline` from a provided list of coordinates.

MKPolyline.coordinates and MKPolyline(coordinates:)

---

CONTRIBUTING.md

I added a section to Contributing.md that suggests users use the 🚀 emoji to indicate that they read our guidelines. We can still leave the checkbox in the PR template. It will be really funny to see who checks the box but hasn't read the document 😆
See Twitter thread:
https://twitter.com/alloy/status/981959592337903618
I also moved the reporting issue section to a more appropriate place IMO.

No Brown M&M's

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/SignedIntegerExtensions.swift
Sources/Extensions/SwiftStdlib/SignedNumericExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

🚀 
Added one method to SignedNumeric extension, and one to SignedInteger extension:
- spelledOutString(locale:)  returns String representation of number spelled in specified locale language
- ordinalString(locale:)  returns String ordinal representation of number in specified locale language

Signed numeric

---

Sources/Extensions/SwiftStdlib/SignedIntegerExtensions.swift
Sources/Extensions/SwiftStdlib/SignedNumericExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwiftStdlibTests/StringExtensionsTests.swift

🚀
This is a really small update just to remove SwiftLint warnings and a dead reference to `FoundationDeprecated.swift`.

Remove warnings and dead references

---

CHANGELOG.md
Sources/Extensions/UIKit/UICollectionViewExtensions.swift
Sources/Extensions/UIKit/UITableViewExtensions.swift
Tests/UIKitTests/UITableViewExtensionsTests.swift

In this PR I am updating:
`dequeueReusableCell(withClass:for)`,
`dequeueReusableHeaderFooterView(withClass)`,
`dequeueReusableCell(withClass)` in **UITableViewExtentions** and  `dequeueReusableCell(withClass:for)`,
`dequeueReusableSupplementaryView(ofKind:withClass:for)` in **UICollectionViewExtentions** 
to return not an optional value. In my opinion is better to get a `fatalError(...)` if the nib file could not be found.

update UITableView and UICollectionView Extensions

---

Sources/Extensions/UIKit/Deprecated/UIKitDeprecated.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwiftStdlibTests/SignedIntegerExtensionsTests.swift

Adding the SwifterSwift Organization name to the project settings, so the new files will no longer be created with \_\_\_ORGANIZATIONNAME\_\_\_ :))

Adding organization name to the project settings

---

CHANGELOG.md
Sources/Extensions/UIKit/UITableViewExtensions.swift
Tests/UIKitTests/UITableViewExtensionsTests.swift

🚀 
This extension will safely scroll UITableView to given IndexPath.

Add safeScrollToRow(at:at:animated:) to safely scroll table view

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
Sources/Extensions/SwiftStdlib/Deprecated/SwiftStdlibDeprecated.swift
Tests/SwiftStdlibTests/CollectionExtensionsTests.swift

Added deprecation warning to Array.groupByKey(keyForValue:) method

---

CHANGELOG.md
Sources/Extensions/UIKit/UIGestureRecognizerExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/UIKitTests/UIGestureRecognizerExtensionsTests.swift

I am unsure as to the changelog - not sure how to add to it exactly.  Could you explain this?
Not sure how I can be sure this supports tvOS, watchOS, etc. If you could explain this as well please, I can add what is needed for this and the changelog and request again.

Add UIGestureRecognizer extension to remove itself from associated view

---

CHANGELOG.md
Sources/Extensions/UIKit/UIScrollViewExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/UIKitTests/UIScrollViewExtensionsTest.swift

Snapshots the entire rendered scroll view, even if it does not show on screen at the moment. Very similar to UIView.screenshot but it returns an image representation of the entire content.

Add UIScrollView extension to snapshot entire scrollview

---

CHANGELOG.md
Sources/Extensions/UIKit/UITextViewExtensions.swift
Tests/UIKitTests/UITextViewExtensionsTests.swift

While `UITextView` is used as a non-scrollable text container (i.e chat bubble) some inset, offset, padding required to set to zero as following
```swift
textView.contentInset = UIEdgeInsets.zero
textView.scrollIndicatorInsets = UIEdgeInsets.zero
textView.contentOffset = CGPoint.zero
textView.textContainerInset = UIEdgeInsets.zero
textView.textContainer.lineFragmentPadding = 0
textView.sizeToFit()
```
This extension `wrapToContent` wrap everything up into a nice little instance method.

 🚀 Wrap to the content (String / AttributedText) UITextView #New-Extension

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/ComparableExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwiftStdlibTests/ArrayExtensionsTests.swift
Tests/SwiftStdlibTests/ComparableExtensionsTests.swift

🚀
This PR adds two extensions to `Comparable`
`isBetween(min:max:)` returns whether or not a `Comparable` is bounded in a range.
`clamp(min:max)` limits a `Comparable` within the provided bounds.

Add `isBetween(min:max:)` and `clamped(min:max:)` Comparable extensions

---

Sources/Extensions/SwiftStdlib/ComparableExtensions.swift
Tests/SwiftStdlibTests/ComparableExtensionsTests.swift

Fixes concerns raised in #466. 
Didn’t add a CHANGELOG since its a recent addition but LMK if its needed.

Fix Comparable extensions to used `ClosedRange` vs `min/max`.

---

Sources/Extensions/SwiftStdlib/ArrayExtensions.swift

Just fixing minor docs issues on some Array extensions.

Fixing some array extensions Docs.

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
Sources/Extensions/SwiftStdlib/CollectionExtensions.swift
Sources/Extensions/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/ArrayExtensionsTests.swift
Tests/SwiftStdlibTests/CollectionExtensionsTests.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

I changed the conformance of most array extensions to Sequence or Collection to expand their possible area of application. Their tests have also been moved to the appropriate files.
fixes #427

Refactor array extensions

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

Add `single(where)` SequenceExtension

---

CHANGELOG.md
Sources/Extensions/UIKit/UIEdgeInsetsExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/UIKitTests/UIEdgeInsetsExtensionsTests.swift
Tests/UIKitTests/UIGestureRecognizerExtensionsTests.swift

Edge insets extensions

---

CHANGELOG.md
Sources/Extensions/UIKit/UIImageExtensions.swift

🚀
Fix an issue where the `init(color:size:)` method had some `guard else { return ... }`s that could put the graphics context in an open state. `UIGraphicsBeginImageContextWithOptions` was called with no `UIGraphicsEndImageContext` to close it.

Ensure that `UIGraphicsEndImageContext` is called.

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
Sources/Extensions/SwiftStdlib/RangeReplaceableCollectionExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwiftStdlibTests/ArrayExtensionsTests.swift
Tests/SwiftStdlibTests/RangeReplaceableCollectionTests.swift

This is still related to #427 
Notice that still has some array extensions that could be refactored. 
@omaralbeik Should we reopened that? Create a new one what do you think?

Changing rotate/rotated Array extensions to RangeReplacebleCollection extensions

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
Sources/Extensions/SwiftStdlib/RandomAccessCollectionExtensions.swift
Sources/Extensions/SwiftStdlib/RangeReplaceableCollectionExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwiftStdlibTests/ArrayExtensionsTests.swift
Tests/SwiftStdlibTests/RandomAccessCollectionExtensionsTests.swift
Tests/SwiftStdlibTests/RangeReplaceableCollectionTests.swift

Continuation of #512 
Still related to #427, hope to find time to take a more detailed look :))

Refactor some other array extensions

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/Deprecated/SwiftStdlibDeprecated.swift
Sources/Extensions/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

Used [RFC 5322](http://emailregex.com/) in `isEmail`, an email address regex that 99.99% works.

Fixes #514

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/DictionaryExtensions.swift
Sources/Extensions/SwiftStdlib/RangeReplaceableCollectionExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwiftStdlibTests/DictionaryExtensionsTests.swift
Tests/SwiftStdlibTests/RangeReplaceableCollectionTests.swift

…to remove a random element from a dictionary

Add 'removeRandomElement()' to Dictionary

---

CHANGELOG.md
Sources/Extensions/UIKit/UIEdgeInsetsExtensions.swift
Tests/UIKitTests/UIEdgeInsetsExtensionsTests.swift

This is useful in some situations, for example:
```
let insets = UIEdgeInsets(top: 10, left: 15, bottom: 20, right: 25)
view.frame.inset(by: insets.insetBy(bottom: 5))
```
vs
```
let insets = UIEdgeInsets(top: 10, left: 15, bottom: 20, right: 25)
let insets2 = UIEdgeInsets(top: insets.top, left: insets.left, bottom: insets.bottom + 5, right: insets.bottom)
view.frame.inset(by: insets2)
```

Add `insetBy(top:left:bottom:right:)` and `insetBy(horizontal:vertical)` to UIEdgeInsets.

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/RangeReplaceableCollectionExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwiftStdlibTests/RangeReplaceableCollectionTests.swift

An convenience init to create a collection of a given size initialized with the values of an expression :))

Collection initializer with an expression.

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/RangeReplaceableCollectionExtensions.swift
Sources/Extensions/UIKit/UIRefreshControlExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/UIKitTests/UIRefreshControlExntesionsTests.swift

When a UIRefreshControl is added as a subview inside of UITableView, then calling the `beginRefresh` method does not show up the UIRefreshControl inside the UITableView. Developer had to manually change the content offset of the UITableView instance.
Source: [Stack Overflow](https://stackoverflow.com/questions/14718850/uirefreshcontrol-beginrefreshing-not-working-when-uitableviewcontroller-is-ins/14719658#14719658)

UIRefreshControl extension added to begin refresh programatically.

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

- ☑︎ I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- ☑︎ New extensions are written in Swift 4.
- ☑︎ New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- ☑︎ I have added tests for new extensions, and they passed.
- ☑︎ All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- ☑︎ All extensions are declared as **public**.
- ☑︎ I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

Add method for first char uppercased in String

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/OptionalExtensions.swift
Tests/SwiftStdlibTests/OptionalExtensionsTests.swift

Add '?=' (ConditionalAssignment) operator to Optional

---

CHANGELOG.md
Sources/Extensions/UIKit/UIViewExtensions.swift

According to [Apple's documentation](https://developer.apple.com/documentation/uikit/nslayoutconstraint/1526955-activate): activating constraints in a bunch is typically more performant than activating them one by one.
- [] New extensions are written in Swift 4.

Performance imporvement in UIView fillToSuperview()

---

Sources/Extensions/UIKit/UICollectionViewExtensions.swift
Sources/Extensions/UIKit/UITableViewExtensions.swift
Tests/SwiftStdlibTests/OptionalExtensionsTests.swift

🚀
Just getting rid of some SwiftLint warnings here, nothing too exciting :)

Fix SwiftLint warnings

---

CHANGELOG.md
Sources/Extensions/Foundation/DataExtensions.swift
Tests/FoundationTests/DataExtensionsTests.swift

🚀
I've found this extension particularly useful when debugging JSON web responses. If you try and just print out the strings lldb prints them out as one big jumbled line, but if you print out these `jsonObject` responses it's _much_ cleaner.
What do you think about this being added to `String` as well?

Data extension for converting to a JSON object

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/DictionaryExtensions.swift
Tests/SwiftStdlibTests/DictionaryExtensionsTests.swift

🚀
These versions of `map` and `compactMap` return a `Dictionary`, rather than an `Array`.
I'm a bit unsure of the function names because of the clash with the built-in `map` and `compactMap` functions.
------------------------------------------------
`map` seems to prioritise the new function. E.g. in
```Swift
let intToString = [0: "0", 1: "1", 2: "2"]
let stringToInt = intToString.map { (key, value) in
return (String(describing: key), Int(value)!)
}
```
`stringToInt ` is of type `[String: Int]`. If you want it to return `[(String, Int)]`, as the original function would do, you need to define the type explicitly. I.e.
```Swift
let stringToInt: [(String, Int)] = intToString.map { (key, value) in
```
------------------------------------------------
`compactMap` actually won't compile in a …

Create mapping functions for Dictionary

---

CHANGELOG.md
Sources/Extensions/UIKit/UIEdgeInsetsExtensions.swift
Tests/UIKitTests/UIEdgeInsetsExtensionsTests.swift

Add addition operator to `UIEdgeInsets`

---

CHANGELOG.md
Sources/Extensions/UIKit/UIImageExtensions.swift
Tests/UIKitTests/UIImageExtensionsTests.swift

🚀
There are 2 versions, one where the angle is passed directly as a `CGFloat` in radians, the other using the `Measurement` class, which is only available for iOS 10+.

Add `rotated(by:)` functions to `UIImage` for generating rotated images.

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/DictionaryExtensions.swift
Tests/SwiftStdlibTests/DictionaryExtensionsTests.swift

🚀
- [x ] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x ] New extensions are written in Swift 4.
- [x ] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [x ] I have added tests for new extensions, and they passed.
- [x ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x ] All extensions are declared as **public**.
- [x ] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

Added 'key(forValue: Value)' method to DictionaryExtensions

---

CHANGELOG.md
README.md
SwifterSwift.podspec

🚀
We need to create a public release to fix the cocoapods issue. Unfortunately https://github.com/SwifterSwift/SwifterSwift/pull/560 was merged before we could create release 4.5.1, so we're stuck with updating the version to 4.6.0.

Update the CHANGELOG to correctly display what has been changed for the latest version

---

README.md

🚀
Hey, sorry I missed this for the 4.6.0 release. Do we need to create a 4.6.1 release now in order to update the README file?

Fix README to say Xcode 10.0 and Swift 4.2

---

CHANGELOG.md
Sources/Extensions/Shared/ColorExtensions.swift

WhatsApp color was missing in the social color constants, added it :-)

Added missing WhatsApp color

---

Sources/Extensions/AppKit/NSImageExtensions.swift
Sources/Extensions/AppKit/NSViewExtensions.swift
Sources/Extensions/Foundation/URLExtensions.swift
Sources/Extensions/Foundation/UserDefaultsExtensions.swift
Sources/Extensions/Shared/ColorExtensions.swift
Sources/Extensions/SwiftStdlib/IntExtensions.swift
Sources/Extensions/SwiftStdlib/OptionalExtensions.swift
Sources/Extensions/SwiftStdlib/StringExtensions.swift
Sources/Extensions/UIKit/UIButtonExtensions.swift
Sources/Extensions/UIKit/UICollectionViewExtensions.swift
Sources/Extensions/UIKit/UIGestureRecognizerExtensions.swift
Sources/Extensions/UIKit/UIImageExtensions.swift
Sources/Extensions/UIKit/UITableViewExtensions.swift
Sources/Extensions/UIKit/UITextFieldExtensions.swift
Sources/Extensions/UIKit/UIViewControllerExtensions.swift
Sources/Extensions/UIKit/UIViewExtensions.swift

Removed "self." calls where not needed. According to most code style guides (for example https://github.com/raywenderlich/swift-style-guide#use-of-self) they should be avoided where possible. What is your opinion about this?
I didn't add a changelog because it's only a style change (or should I?).
- [x ] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.

Removed self. when not needed

---

CHANGELOG.md
Sources/Extensions/Foundation/DateExtensions.swift
Sources/Extensions/Foundation/Deprecated/FoundationDeprecated.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/FoundationTests/DateExtensionsTests.swift

🚀
I wasn't liking the old random function, it makes more sense to use the built-in style.
I really wished they'd created a `Randomizable` protocol to generalise its usage elsewhere.

Replace the old Date.random function with ones using the new built-in random API

---

CHANGELOG.md
Sources/Extensions/Dispatch/DispatchQueueExtensions.swift
SwifterSwift.podspec
SwifterSwift.xcodeproj/project.pbxproj
Tests/DispatchTests/DispatchQueueExtensionsTests.swift

Add `isMainQueue` to check if current queue is main queue, add `isCurrent(_:)` to check if current queue is specified queue. It's very useful to avoid `sync` on a serial queue. eg:
```Swift
if DispatchQueue.isMainQueue { 
return
}
let logQueue = DispatchQueue(label: "logQueue")
if DispatchQueue.isCurrent(logQueue) {
return 
}
```

Add new extensions of `DispatchQueue`

---

CHANGELOG.md
Sources/Extensions/Foundation/DateExtensions.swift
Sources/Extensions/Foundation/Deprecated/FoundationDeprecated.swift
Tests/FoundationTests/DateExtensionsTests.swift

🚀
`Date` objects do not have any information about timezones. They're a representation of a specific point in time, doesn't matter where in the world. This was causing confusion in some of the unit tests that were using it without realising that it was wrong, which were fixed in https://github.com/SwifterSwift/SwifterSwift/pull/592.

Remove `timeZone` from `Date` extensions

---

Sources/Extensions/UIKit/UITableViewExtensions.swift

- [x ] New extensions are written in Swift 4.
- [x ] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [x ] I have added tests for new extensions, and they passed.
- [x ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x ] All extensions are declared as **public**.
- [ x] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

Fixed typos in UITableViewExtensions.swift

---

CHANGELOG.md
Sources/Extensions/Foundation/NSAttributedStringExtensions.swift
Tests/FoundationTests/NSAttributedStringExtensionsTests.swift

Fixing #616 bug on NSAttributedStringExtensions.

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/CollectionExtensions.swift
Tests/SwiftStdlibTests/CollectionExtensionsTests.swift

This PR addresses issue #636 by removing 
* `firstIndex(where: )`
* `firstIndex(of:)`
* `lastIndex(where: )`
* `lastIndex(of:)`
and their related tests.
They should be removed since they are now (since swift 4.2) part of the Swift Standard Library.
See: [SE-0204](https://github.com/apple/swift-evolution/blob/master/proposals/0204-add-last-methods.md)
- [ x ] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ x ] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

removing extensions not needed anymore

---

Sources/Extensions/CoreGraphics/CGPointExtensions.swift
Sources/Extensions/CoreGraphics/CGVectorExtensions.swift
Sources/Extensions/Foundation/DateExtensions.swift
Sources/Extensions/Shared/ColorExtensions.swift
Sources/Extensions/SwiftStdlib/DoubleExtensions.swift
Sources/Extensions/SwiftStdlib/FloatExtensions.swift
Sources/Extensions/SwiftStdlib/FloatingPointExtensions.swift
Sources/Extensions/SwiftStdlib/IntExtensions.swift
Sources/Extensions/SwiftStdlib/SignedIntegerExtensions.swift
Sources/Extensions/SwiftStdlib/SignedNumericExtensions.swift
Sources/Extensions/SwiftStdlib/StringExtensions.swift
Sources/Extensions/UIKit/UITextViewExtensions.swift
Sources/Extensions/UIKit/UIViewExtensions.swift
Tests/FoundationTests/DateExtensionsTests.swift
Tests/SharedTests/ColorExtensionsTests.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift
Tests/UIKitTests/UIViewExtensionsTests.swift

:rocket: It seems like SwifterSwift was using some outdated SwiftLint syntax for `disable next` and they were added in wrong places (not just above the line they were intended to apply to).

Fixed all SwiftLint(0.31.0)-related warnings

---

CHANGELOG.md
Sources/Extensions/UIKit/UIImageExtensions.swift

Fixing tint UIImage extension upside down.

---

CHANGELOG.md
Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
Sources/Extensions/SwiftStdlib/RangeReplaceableCollectionExtensions.swift
Tests/SwiftStdlibTests/ArrayExtensionsTests.swift
Tests/SwiftStdlibTests/RangeReplaceableCollectionTests.swift

Making keep(while: ), take(while: ) and skip(while:) array extensions, collection extensions.
Just want to use them with other types 😅

Making some array extensions, generic collection extensions

---

CHANGELOG.md
Sources/Extensions/MapKit/MKMapViewExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/MapKitTests/MKMapViewTests.swift

Similar to `UITableView`, `MapView` should have the same methods for registering and dequeueing. What do you think about this?

Added MKMapViewExtensions

---

CHANGELOG.md
Sources/Extensions/Foundation/DateExtensions.swift
Tests/FoundationTests/DateExtensionsTests.swift

Fixes method Date.tomorrow (Pair of #641 )

Fix tomorrow to use Calendar.date(byAdding:to:) (Related to Issue #640)

---

README.md

This documents support for the new SwiftPM based dependency manager [Accio](https://github.com/JamitLabs/Accio).
Please note that this project is part of Accio's official [integration tests](https://github.com/JamitLabs/Accio/tree/work/1000-frameworks/Demo/Shared/AppDependencies) within the [Demo project](https://github.com/JamitLabs/Accio/tree/work/1000-frameworks/Demo).

[README] Document support for installation via Accio

---

.github/PULL_REQUEST_TEMPLATE.md

Update Swift version to 5.0 in new PR template

Update Swift version to 5.0 in PR template

---

CHANGELOG.md
Sources/SwifterSwift/Foundation/URLExtensions.swift

`queryValue` extension refactored. Issue discussed in [#661.](https://github.com/SwifterSwift/SwifterSwift/issues/661)

Refactored the query value extension in URL

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

Check if string is palindrome
`"Mom".isPalindrome // true`

✨ Added String.isPalindrome

---

Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift

SwiftLint was complaining about someone else's extension (2 Empty Lines) and I fixed it.

Fixed SwiftLint Warnings

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/CharacterExtensions.swift
Tests/FoundationTests/XCTestManifests.swift
Tests/SwiftStdlibTests/CharacterExtensionsTests.swift
Tests/SwiftStdlibTests/XCTestManifests.swift

Hello.
This pull request fixes #673.

Removed isNumber, isLetter, isLowercased, isUppercased and isWhiteSpace

---

README.md

add missing 'SwifterSwift/UIKit'

add missing 'SwifterSwift/UIKit' to README.md

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UITableViewExtensions.swift
Tests/UIKitTests/UITableViewExtensionsTests.swift

On #695, @LucianoPAlmeida raised a point about `isValidIndexPath(_:)` checking for IndexPaths with negative rows/sections on CollectionViews. This PR updates the TableView's behavior to keep them consistent.

🚀`isValidIndexPath(_:)` will now return `false` for IndexPaths with a negative row or section

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UICollectionViewExtensions.swift
Tests/UIKitTests/UICollectionViewExtensionsTests.swift

Porting #441 to a UICollectionView equivalent

🚀 Added `isValidIndexPath(_:)` UICollectionView method and test

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIImageExtensions.swift

Modifed the scale methods in UIImageExtensions.swift, to use the original scale of the source image.
Use the original scale is a good practice. [PR446](https://github.com/SwifterSwift/SwifterSwift/pull/446) doesn't work because it confuse the local variable "scale" and the image's property "scale".
So, I fix it by this:
Refer:
[PR446](https://github.com/SwifterSwift/SwifterSwift/pull/446)
[PR515](https://github.com/SwifterSwift/SwifterSwift/pull/515)

Use the original scale of the source image

---

.github/stale.yml

See Issue #644 
Also see https://github.com/probot/stale
It's a default configuration with 30 Days until stale (label `won't fix`) and another 7 days until close.  It ignores issues with the label `help wanted`.
Additionally it has the following close comment:
> This issue has been automatically closed because it has not had recent activity. Thank you for your contributions.
When this is merged we have to setup the probot for this repository: https://github.com/apps/stale
(I'll request the add of the app as soon as this is merged. **The Org administrator has to verify this**.)
Since it doesn't add anything to the library itself, I haven't added a changelog entry.

Add a probot stale configuration

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/ArrayExtensions.swift
Tests/SwiftStdlibTests/ArrayExtensionsTests.swift

🚀 Fixed #653. Added **withoutDuplicates(keyPath:)** to **Array**.

Array.withoutDuplicates(keyPath:)

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

🚀 This extension also comes from Paul Hudson at Hacking with Swift. It provides a clean method to add a prefix to a string. If the string already has that prefix, it simply returns the original string.
https://www.hackingwithswift.com/articles/141/8-useful-swift-extensions

String with prefix

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIImageExtensions.swift
Tests/UIKitTests/UIImageExtensionsTests.swift

This extension allows to specify a background color for partially transparent UIImages.
I also changed my old username in the changelog to my new one.

Add withBackgroundColor(_:) extensions to UIImage

---

CHANGELOG.md
Sources/SwifterSwift/AppKit/NSColorExtensions.swift
Sources/SwifterSwift/UIKit/UIColorExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/AppKitTests/NSColorExtensionsTests.swift
Tests/UIKitTests/UIColorExtensionsTests.swift

This extension allows to create an NSColor or UIColor with different colors for light mode and dark mode. I created separate `NSColorExtensions.swift` and `UIColorExtensions.swift` files, because NSColor and UIColor use different APIs for this problem and can't be unified.
I couldn't figure out how to create a test for macOS, because it uses NSAppearance instead of UITraitCollection. Any suggestions?

Add init(light:dark:) to NSColor and UIColor

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

🚀 Sum up a Numeric property, referenced by KeyPath, of all elements in a sequence. Originally from https://swiftbysundell.com/articles/reducers-in-swift/.
Resolves #735

Add sum(for keyPath:) to Sequence

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIImageExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj

🚀 This provides a fix for Issue #732. In iOS/tvOS 10, Apple introduced the [UIGraphicsImageRenderer API](https://developer.apple.com/documentation/uikit/uigraphicsimagerenderer), which effectively replaces the older `UIGraphicsImageContext` method this method was using before
I didn't add any new extensions in this PR. I changed the internals of one to use a newer API, but everything looks exactly the same to a consumer of the method, and all the pre-existing tests pass. Do I need to check any of the other boxes?

🚀 UIGraphicsImageRenderer in filled(withColor:)

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIImageExtensions.swift

- This PR improve the UIImage.tint(color:blendMode:) function using UIGraphicsImageRenderer as specified in the #731 issue.

Improve UIImage.tint(color:blendMode:) using UIGraphicsImageRenderer

---

.travis.yml

Looks like the possible destinations in the Travis builds have changed for watchOS, which is why all the other builds are failing

Fix watchOS destination

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIImageExtensions.swift
Tests/UIKitTests/UIImageExtensionsTests.swift

When you want to create an UIImage using a base 64 string.
- [?] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
?  (it compiled without errors or warnings without changing the deployment target so it should work right?)

adding base64 UIImage initialiser #741 

---

.travis.yml
README.md
Sources/SwifterSwift/AppKit/NSColorExtensions.swift
Sources/SwifterSwift/AppKit/NSImageExtensions.swift
Sources/SwifterSwift/AppKit/NSViewExtensions.swift
Sources/SwifterSwift/CoreGraphics/CGColorExtensions.swift
Sources/SwifterSwift/CoreGraphics/CGFloatExtensions.swift
Sources/SwifterSwift/CoreGraphics/CGPointExtensions.swift
Sources/SwifterSwift/CoreGraphics/CGSizeExtensions.swift
Sources/SwifterSwift/Foundation/DateExtensions.swift
Sources/SwifterSwift/Foundation/NSAttributedStringExtensions.swift
Sources/SwifterSwift/Shared/ColorExtensions.swift
Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
Sources/SwifterSwift/UIKit/UIAlertControllerExtensions.swift
Sources/SwifterSwift/UIKit/UITextViewExtensions.swift
SwifterSwift.podspec
Tests/AppKitTests/NSColorExtensionsTests.swift
Tests/CoreGraphicsTests/CGColorExtensionsTests.swift
Tests/FoundationTests/NSAttributedStringExtensionsTests.swift
Tests/SharedTests/ColorExtensionsTests.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift
Tests/UIKitTests/UITextViewExtensionsTests.swift
Tests/UIKitTests/UIViewControllerExtensionsTests.swift

🚀
Fix imports and tests for Xcode 11.2 and macCatalyst. I fixed some of the tests for macCatalyst but there are a few with incredibly strange results. At the very least this can now be used and tested with Xcode 11.2.

Xcode 11.2

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/DictionaryExtensions.swift
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/DictionaryExtensionsTests.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

Add `init(grouping:by:)` for Dictionary that uses a keypath. 🚀

---

Sources/SwifterSwift/UIKit/UIImageExtensions.swift

Modified UIImage extension compressed so it doesn't use other extensions, fixes #757  🚀
- [ x] New extensions are written in Swift 5.0.
- [ x] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
- [ x] I have added tests for new extensions, and they passed.
- [x ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ x ] All extensions are declared as **public**.

Modified UIImage extension compressed so it doesn't use other extensions

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/CollectionExtensions.swift

🚀
This change allows the function to be used on `String`, for example.

Make group(by:) generic for all Collections

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIImageExtensions.swift
Tests/UIKitTests/UIImageExtensionsTests.swift

🚀 Base64-encode a `UIImage`s `pngData()` and `jpegData(compressionQuality:)` and return it as a string.
Resolves #742

Add base64String methods to UIImage

---

CHANGELOG.md
Sources/SwifterSwift/AppKit/NSColorExtensions.swift
Sources/SwifterSwift/AppKit/NSImageExtensions.swift
Sources/SwifterSwift/AppKit/NSViewExtensions.swift

- [/] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [/] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

Exclude AppKit extensions to be compiled for macCatalyst

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

🚀 Added a new version of Sequence.map that uses `KeyPath` to map elements.

Sequence.mapByKeyPath

---

Tests/SwiftStdlibTests/KeyedDecodingContainerExtensionsTests.swift

🚀 Fixed build errors in `KeyedDecodingContainerTests` caused by `try!`.

Fixed build errors in KeyedDecodingContainerTests

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

🚀 Added a new version of `Sequence.compactMap` that uses `KeyPath` to map elements (proposed by @guykogus in https://github.com/SwifterSwift/SwifterSwift/pull/763#discussion_r348835443).

Sequence.compactMapByKeyPath

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift
Tests/SwiftStdlibTests/TestHelpers.swift

🚀 Added `Sequence.filter(by:)` similar to [map](https://github.com/SwifterSwift/SwifterSwift/pull/763) and [compactMap](https://github.com/SwifterSwift/SwifterSwift/pull/766).

Filter by key path

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/ArrayExtensions.swift
Tests/SwiftStdlibTests/ArrayExtensionsTests.swift

Add sorted(like:keyPath:) to Array to sort an array like another array based on a keyPath.
- [/] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [/] New extensions are written in Swift 5.0.
- [/] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
- [/] I have added tests for new extensions, and they passed.
- [/] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [/] All extensions are declared as **public**.
- [/] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

Add sorted(like:keyPath:) to Array

---

.codecov.yml

Our code coverage reports don't work anymore in the new Github actions CI. 
It needs a token. It worked on Travis because:
So adding the token then ...

[GitHub Actions] Fix code coverage report

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/MutableCollectionExtensions.swift
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/MutableCollectionTests.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift
Tests/SwiftStdlibTests/TestHelpers.swift

…and:and:) to sort collections/sequences by multiple key paths

Enable sequence and collection to be sorted by multiple key paths

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

Just making the base 64 decode safe decoding by including padding. 
Fixes #795

[BugFix] Making String.base64Decoded a safe base64 decode  by including padding.

---

Package.swift

In #800 min. target was updated to iOS 10. When using SPM, target is set as oldest supported by SDK. This PR adds min. target to Package.swift. Without it, the compiler fails due to iOS 9 availability checks.
> This predefined deployment version will be the oldest deployment target version supported by the installed SDK for a given platform.
https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#supportedplatform

Add min. platform to SPM

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIImageExtensions.swift
Tests/UIKitTests/UIImageExtensionsTests.swift

Fix image cropped issue when scale not equal to 1

---

CHANGELOG.md
Sources/SwifterSwift/Foundation/LocaleExtensions.swift
Tests/FoundationTests/LocaleExtensionsTests.swift

Convert ISO region code into flag emoji

---

.swiftlint.yml
CHANGELOG.md
Dangerfile
Sources/SwifterSwift/Foundation/NotificationCenterExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/FoundationTests/NotificationCenterExtensionsTests.swift

🚀
Sometimes you just want to know if a notification has been sent only once (e.g. when internet connection has been recovered).

Observe a single posting of a notification

---

CHANGELOG.md
README.md
Sources/SwifterSwift/CoreGraphics/CGRectExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/CoreGraphicsTests/CGRectExtensionsTests.swift

- Added property `center`.
- Added initializer `init(center:size:)` to create `CGRect` with center and size.
- Added `resizing(to:anchor:)` to create `CGRect` by resizing with anchor.

Added CGRect extensions and its tests

---

CHANGELOG.md
Sources/SwifterSwift/Foundation/URLExtensions.swift
Tests/FoundationTests/URLExtensionsTests.swift

🚀
I often have an object loaded from a server that has optional paths, e.g.
```Swift
struct Food: Codable {
imagePath: String?
}
```
With this extension users can simply call
```Swift
if let imageURL = URL(food.imagePath) { ... }
```
instead of
```Swift
if let imagePath = food.imagePath,
let imageURL = URL(imagePath) { ... }
```
Alternatively I could have defined the property as `imagePath: URL?`, but I don't do this for decoded values because if the URL is invalid the entire decoding process fails as opposed to just returning `nil`, so this allows for smoother error handling.

Add initializer for a `URL` with an optional `String`

---

.swiftlint.yml
CHANGELOG.md
Sources/SwifterSwift/CoreAnimation/CATransform3DExtensions.swift
Sources/SwifterSwift/CoreGraphics/CGAffineTransformExtensions.swift
Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
Sources/SwifterSwift/UIKit/UIViewExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/CoreAnimationTests/CAGradientLayerExtensionsTests.swift
Tests/CoreAnimationTests/CATransform3DExtensionsTests.swift
Tests/CoreGraphicsTests/CGAffineTransformExtensionsTests.swift

🚀
CATransform only had the old Objective-C-style functions. It now gets the same treatment as `CGAffineTransform`, plus `mutating` functions to go with it.
Also added in a little fix for `CAGradientLayerExtensionsTests`, which wasn't included in all the tests.

Make CATransform3D Swifty

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/RangeReplaceableCollectionExtensions.swift
Tests/SwiftStdlibTests/RangeReplaceableCollectionTests.swift

🚀
This is especially useful for `String`s.

Access/update RangeReplaceableCollection by index offsets

---

CHANGELOG.md
Sources/SwifterSwift/Foundation/NSAttributedStringExtensions.swift
Tests/FoundationTests/NSAttributedStringExtensionsTests.swift

Make `NSAttributedString.applying(attributes:)` public

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

Simple sugar to find an element in sequence using KeyPath

Added `first(by:equal:)` extension to Sequence

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

Adding `last(where:equals:)` extension to Sequence in addition to `first(where:equals:)`.

Added `last(where:equals:)` extension to Sequence

---

CHANGELOG.md
Sources/SwifterSwift/CoreGraphics/CGSizeExtensions.swift
Tests/CoreGraphicsTests/CGSizeExtensionsTests.swift

Added new `+`, `+=`, `-` and `-=` operator extensions for scalar.

CGSize: Added new `+`, `+=`, `-` and `-=` operator extensions for tuple

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIColorExtensions.swift
Tests/UIKitTests/UIColorExtensionsTests.swift

See the earlier [discussion][link1] about the reason for creating this PR.
For `NSColor`, since `init (cgColor:)` returns an optional value, it may cause a break change. We may need further discussion.
[link1]:https://github.com/SwifterSwift/SwifterSwift/pull/722#issuecomment-629224728

Refactored init(light:dark:) to remove deployment target version restrictions.

---

CHANGELOG.md
Sources/SwifterSwift/CoreAnimation/CAGradientLayerExtensions.swift

CoreAnimation: Make CAGradientLayer extension public.

---

CHANGELOG.md
Sources/SwifterSwift/Dispatch/DispatchQueueExtensions.swift
Tests/DispatchTests/DispatchQueueExtensionsTests.swift

Added convenient wrapper to asyncAfter

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/Deprecated/StdlibDeprecated.swift
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

🚀
Hello.
In this pull request I fixed #861.

Deprecated map(by:), compactMap(by:), filter(by:)

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIViewExtensions.swift
Tests/UIKitTests/UIViewExtensionsTests.swift

Sometimes we need to set `masksToBounds` property of `UIView` from storyboard.

Added `masksToBounds` (IBInspectable) extension

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/DoubleExtensions.swift
Sources/SwifterSwift/SwiftStdlib/FloatExtensions.swift
Sources/SwifterSwift/SwiftStdlib/FloatingPointExtensions.swift
Tests/SwiftStdlibTests/DoubleExtensionsTests.swift
Tests/SwiftStdlibTests/FloatExtensionsTests.swift
Tests/SwiftStdlibTests/FloatingPointExtensionsTests.swift

🚀
The underlying function is generic, so might as well do the same.

Make √ generic for FloatingPoint values

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIViewExtensions.swift
Tests/UIKitTests/UIViewExtensionsTests.swift

Handy helpers for finding existing constraints on a view. Under the hood they use `allConstraints`, which enumerates all ancestors to find all constraints for a view. See #879.

constraint finders (widthConstraint, heightConstraint, leadingConstraint, trailingConstraint, topConstraint, bottomConstraint)

---

Sources/SwifterSwift/UIKit/UIViewExtensions.swift

Added a note that I often forget to UIView addShadow(ofColor: radius: offset: opacity:)

Added note for UIView.addShadow()

---

CHANGELOG.md
Sources/SwifterSwift/Shared/ColorExtensions.swift
Sources/SwifterSwift/UIKit/UIImageExtensions.swift
Tests/UIKitTests/UIImageExtensionsTests.swift

Calculates the average color for an entire UIImage. This is useful for determining whether an image is light or dark, among other things. See #879.

UIImage.averageColor

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIViewExtensions.swift
Tests/UIKitTests/UIViewExtensionsTests.swift

Fixes #622 
* This may cause issues in users who use those properties in storyboard as `@IBInspectable`.

Rename conflicting UIView shadowExtensions

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
Sources/SwifterSwift/SwiftStdlib/StringProtocolExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift
Tests/SwiftStdlibTests/StringProtocolExtensionsTests.swift

New String regex extensions as discussed in #896:
```swift
func matches(regex: NSRegularExpression) -> Bool
func replacingOccurrences(of pattern: String, with template: String, range searchRange: Range<String.Index>? = nil) -> String
func replacingOccurrences(of regex: NSRegularExpression, with template: String, range searchRange: Range<String.Index>? = nil) -> String
static func ~= (lhs: String, rhs: NSRegularExpression) -> Bool
```
Once I get the thumbs up I'll add the changelog.

extensions & tests

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/CollectionExtensions.swift
Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/CollectionExtensionsTests.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

🚀
I can't believe we don't have these. They're essential for every project I've worked on...

Add range extensions for String

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIImageExtensions.swift

Fix bug. When UIImage rotated, it lost origin scale.

fix bug: Rotated UIImage lose origin scale and blured.

---

CHANGELOG.md
Sources/SwifterSwift/SceneKit/SCNVector3Extensions.swift
Tests/SceneKitTests/SCNVector3ExtensionsTests.swift

Closes #907
The function uses the SIMD function `normalize` to scale the vector to have a length of 1, while still keeping the same trajectory.
> In mathematics, a unit vector in a normed vector space is a vector (often a spatial vector) of length 1.

SCNVector3 normalize() / divide

---

Sources/SwifterSwift/UIKit/UITextViewExtensions.swift

The change was autocorrected using swiftlint itself.

chore: reenable rule legacy_constructor 🚀

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIAlertControllerExtensions.swift

Making alert controller show extension unavailable for app extensions

---

CHANGELOG.md
Sources/SwifterSwift/Shared/ColorExtensions.swift

Use `enum` to declare a namespace, instead of `struct`.
The difference of using enum and struct is,  if struct is used, we need to make `init` private to prevent user create an instance of this namespace.
Like the following shows: https://github.com/SwifterSwift/SwifterSwift/blob/61187db25876a8bb3cb49548478d072bdefb52a5/Sources/SwifterSwift/Shared/ColorExtensions.swift#L365-L368
https://github.com/SwifterSwift/SwifterSwift/blob/61187db25876a8bb3cb49548478d072bdefb52a5/Sources/SwifterSwift/Shared/ColorExtensions.swift#L458-L461
https://github.com/SwifterSwift/SwifterSwift/blob/61187db25876a8bb3cb49548478d072bdefb52a5/Sources/SwifterSwift/Shared/ColorExtensions.swift#L1294-L1297
And it's easy to forget to do the protection like:
https://github.com/SwifterSwift/SwifterSwift/blob/61187db25876a …

Modify Namespaces in ColorExtensions

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/BidirectionalCollectionExtensions.swift
Sources/SwifterSwift/SwiftStdlib/Deprecated/StdlibDeprecated.swift
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/BidirectionalCollectionExtensionsTests.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

Also added `contains(_:)` for `Hashable` elements

Improve `Sequence` extensions with cleaner code and performance improvements

---

CHANGELOG.md
Sources/SwifterSwift/Foundation/MeasurementExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/FoundationTests/MeasurementExtensionsTests.swift

Add static initializers to create measurement instances presenting angle in various unit types.
My goal is to make the following form when calling rotate functions in `UIImage`:
```swift
image.rotated(by: .degrees(90))
```
and later for `UIView`:
```swift
view.rotated(by: .degrees(90))
```

Add New Extension `MeasurementExtensions`

---

Sources/SwifterSwift/UIKit/UIViewExtensions.swift

Cleaning up some outdated `@available` attribute declaration for `iOS 9`.

Cleanup `@available` attribute declaration that doesn't need anymore.

---

Sources/SwifterSwift/Shared/ColorExtensions.swift
Tests/SharedTests/ColorExtensionsTests.swift

--------
If the hex string is "0XFFFFFF", `hexString.replacingOccurrences(of: "0x", with: "")` do nothing, `0X` will not be removed, so i add `lowercased` .
I think it was a mistake due to carelessness. 😄

fix replace "0x" bug

---

CHANGELOG.md
Sources/SwifterSwift/Foundation/URLExtensions.swift
Tests/FoundationTests/URLExtensionsTests.swift

Apple developers frequently need to interface with networking requests and file systems. 
However, it can be inconvenient when the `URL` string initializer returns an optional `URL`, especially when developers put hard-coded URL string that should never fail to unwrap.
Unwrapping with`!` symbol that decreases code-readability and adds ceremony:
```swift
let website = URL(string: "https://www.youtube.com")!
```
By adding a new class initializer in extension to `URL`, SwifterSwift can provide a syntactical sugar to initialize `URL` from string and implicitly force unwrap the `URL`
Now, developers can do:
```swift
let website = URL(unsafeString: "https://developer.apple.com/wwdc21/")
```
The `URL(string: )` initializer is not impacted and can still be used.
One might argue that this addition …

Add unsafeString initializer for URL

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/ArrayExtensions.swift
Sources/SwifterSwift/SwiftStdlib/RangeReplaceableCollectionExtensions.swift
Tests/SwiftStdlibTests/ArrayExtensionsTests.swift

The concept of optional types has been deeply ingrained into the design of Swift, and developers deal with appending optional elements to an array often.
It can be very inconvenient to be first unwrap optional, and append it:
```swift
var foo: [Double] = []
let bar: Double? = 69.0
if let unwrappedBar = bar {
foo.append(unwrappedBar)
}
//or
if bar != nil {
foo.append(bar!)
}
```
By moving the logic of optional unwrap and checking to an `Array` extension method, developers can now use syntactical sugar:
```swift
var foo: [Double] = []
let bar: Double? = 69.0
foo.append(bar)
```

Array append for optional element and sequences

---

CHANGELOG.md
Sources/SwifterSwift/Shared/ColorExtensions.swift
Tests/SharedTests/ColorExtensionsTests.swift

Add `init?(argbHexString:)` to support the common ARGB format used in Android

---

.github/workflows/CI.yml

As described here https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/
This virtual environment was removed, that is why PRs like #985 and #987 are just failing the jobs.

[Actions] Update Linux job ubuntu virtual machine

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIButtonExtensions.swift
Tests/UIKitTests/UIButtonExtensionsTests.swift

🚀
Hello.
Add `setAttributedTitleForAllStates` and some other related functions.
Fixed #1000.

func setAttributedTitleForAllStates(_ title: NSAttributedString)

---

CHANGELOG.md
Sources/SwifterSwift/Foundation/URLExtensions.swift
Tests/FoundationTests/URLExtensionsTests.swift

deletingAllPathComponents can now handle empty paths.

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIViewExtensions.swift
Tests/UIKitTests/UIViewExtensionsTests.swift
Tests/XCTest/XCTestExtensions.swift

Fixes #935 by getting the current angle of the transform and then rotating.

Fixes UIView.rotate(toAngle)

---

CHANGELOG.md
README.md
Sources/SwifterSwift/CryptoKit/DigestExtensions.swift
SwifterSwift.podspec
SwifterSwift.xcodeproj/project.pbxproj
Tests/CryptoKitTests/DigestExtensionsTests.swift

hexString computed property for CryptoKit.Digest

---

Brewfile
Brewfile.lock.json

Seems like we don't use this anyways, and since it is failing the CI. Let's see if we really don't use it ...

Removing Xctool from project

---

Tests/UIKitTests/UIButtonExtensionsTests.swift

🚀
Hello.
Found out that if `accuracy == 1.0` then `UIColor.red == UIColor.green`. We should use a value close to 0.

Hotfix accuracy

---

Sources/SwifterSwift/CryptoKit/DigestExtensions.swift

Updated `.hexString` in `DigestExtensions`, with a workaround for a compile-time error on Xcode 14 Beta.
Refer to the issue:  https://github.com/SwifterSwift/SwifterSwift/issues/1042
Refer to the bug: https://github.com/apple/swift/issues/60958

[FIX] - Updated DigestExtensions to compile on Xcode 14 Beta

---

CHANGELOG.md
Sources/SwifterSwift/Foundation/DateExtensions.swift
Tests/FoundationTests/DateExtensionsTests.swift

fix nearestTenMinutes rounding behavior to behavior like nearestHalfHour
As can be seen in the screenshot, nearestTenMinutes, if the minute is halfway of the target interval period (aka multiple of 5 that ends in 5), rounds down.  nearestHalfHour, rounds up when the minute is halfway between a period range
This PR aligns behavior expectations on similarly named computed variables

fix nearestTenMinutes behavior

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIButtonExtensions.swift

Fix #1061. Add `. focused`.
Later I can add `titleForFocused`, `imageForFocused` and other similar methods.

Add .focused

---

Sources/SwifterSwift/SwiftStdlib/DefaultStringInterpolationExtensions.swift

Use `appendInterpolation(_:)` instead of `appendLiteral(_:)` for better handling interpolation behavior.

Modify Implementation of `DefaultStringInterpolation.appendInterpolation(_:placeholder:where:)`

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/CollectionExtensions.swift
Tests/SwiftStdlibTests/CollectionExtensionsTests.swift

Added a new function `pairs` to the collection extension to generate unique pairs of elements.

Added `pairs` function to Collection 

---

CHANGELOG.md
Sources/SwifterSwift/Foundation/NotificationCenterExtensions.swift

Fixed warning in `observeOnce` that about capture in sendable closure.

Remove warning in NotificationCenterExtensions.swift

---

.github/workflows/CI.yml

As per https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources 18.04 is deprecated.

Upgrade deprecated linux version

---

Sources/SwifterSwift/SwiftStdlib/OptionalExtensions.swift

- Updated the `isNilOrEmpty` and `nonEmpty` boolean computed variables of Optional Collections.
- In existing implementation, it was using guard statements to unwrap optionals and check for nil. However, this is not efficient, considering the Collection (on which this is applied) can itself be very huge in terms of space. And assigning again the large amount of data in some temporary variable is an overhead and consumes extra O(n) space complexity. 
- Also, the collection could be multi-dimensional.
- My approach to this is simple, we do some checks directly on the collection not on temporary variables, considering we aren't using the temporary variable except for checking the nil and empty scenarios.
- I believe newer implementation is more readable and concise.
I created one playground …

Minor changes in Optional Collection extensions. :rocket:

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

Fixed `String.subscript(safe:)` to correctly check for valid ranges of different types

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/Deprecated/StringDeprecated.swift
Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/SwiftStdlibTests/StringExtensionsTests.swift

Deprecate `String.init(randomOfLength:)` in favor of `String.random(ofLength:)`

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
Tests/SwiftStdlibTests/StringExtensionsTests.swift

🚀
Fixes #1109, where performing `switch` on a `String` was broken because the order used in `~=` was reversed.

Reverse the parameters for the ~= String operator to not break the default implementation

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIStackViewExtensions.swift
Tests/UIKitTests/UIStackViewExtensionsTests.swift

In versions below iOS 14, UIStackView is a non-rendering component, that is, the background color cannot be set through the backgroundColor property. Extend a property backgroundViewColor for UIStackView to set its background color.

Feature Extend a property backgroundViewColor for UIStackView to set its background color

---

CHANGELOG.md
Sources/SwifterSwift/Shared/EdgeInsetsExtensions.swift
Sources/SwifterSwift/UIKit/UIAlertControllerExtensions.swift
Sources/SwifterSwift/UIKit/UITabBarExtensions.swift

I used Xcode 15 Beta 7 to detect compilation errors when trying to build product library `SwifterSwift` for Apple Vision Pro and the changes in this PR will fix the encountered compilation errors.
P.S.: This PR does not fix compilation errors for test target `SwifterSwiftTests` but this is also not relevant for consumers.

Fix: compilation errors for visionOS platform

---

CHANGELOG.md
Sources/SwifterSwift/Foundation/URLRequestExtensions.swift
Tests/FoundationTests/URLRequestExtensionsTests.swift

I have a bunch of operators to handle `URLRequest` creation in an easy way. This one is the first of them, to set the `httpMethod`. My idea is to make a PR for each of the operators so in the end we could create requests like this:
```swift
let request = URLRequest(url: url)
.method("post")
.authorization(token: token)
.header(name: "something", value: "interesting")
.jsonBody(parameters)
```

Add `method` operator to URLRequest

---

CHANGELOG.md
Sources/SwifterSwift/Foundation/URLRequestExtensions.swift
Tests/FoundationTests/URLRequestExtensionsTests.swift

Following the idea of the [#1133](https://github.com/SwifterSwift/SwifterSwift/pull/1133), this PR adds a method to URLRequest to set a header.

Add `header(name:, value:)` method to URLRequest

---

CHANGELOG.md
Examples/Examples.playground/Pages/03-UIKitExtensions.xcplaygroundpage/Contents.swift
Package.swift
Sources/SwifterSwift/UIKit/UIViewExtensions.swift

Fix UIView.GradientDirection access level

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/Deprecated/UIImageViewDeprecated.swift
Sources/SwifterSwift/UIKit/UIImageViewExtensions.swift
Sources/SwifterSwift/UIKit/UIViewExtensions.swift
SwifterSwift.xcodeproj/project.pbxproj
Tests/UIKitTests/UIImageViewExtensionsTests.swift
Tests/UIKitTests/UIViewExtensionsTests.swift

Moves blur function to UIView, as it is not only for UIImageView

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIViewExtensions.swift
Tests/UIKitTests/UIViewExtensionsTests.swift

Add a function that makes a UIView instance a circular shape.

Add makeCircle function inside UIViewExtensions

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

🚀
Added `product()` and `product(for:)` methods for multiplying elements and properties in a sequence (standalone PR as requested on #1167).

Added `product()` and `product(for:)` methods to `Sequence`

---

CHANGELOG.md
Package.swift
Sources/SwifterSwift/Resources/PrivacyInfo.xcprivacy

🚀
Fixes #1171
The only usage we have to declare is from https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401
> C56D.1
>> Declare this reason if your third-party SDK is providing a wrapper function around user defaults API(s) for the app to use, and you only access the user defaults APIs when the app calls your wrapper function. This reason may only be declared by third-party SDKs. This reason may not be declared if your third-party SDK was created primarily to wrap required reason API(s).
>>
>> Information accessed for this reason, or any derived information, may not be used for your third-party SDK’s own purposes or sent off-device by your third-party SDK.

Add a privacy manifest

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

🚀
Methods with mapping alternatives: `sorted(by:)`, `sorted(by:with:)`, `sorted(by:and:)`, `sorted(by:and:and:)`, `sum(for:)`, `first(where:equals:)`. All of this keeps compatibility as passing a `KeyPath` will make the code opt for the KeyPath version of the method. (Standalone PR as requested on #1167)

Added mapping functions to `Sequence` as alternatives to `KeyPath`

---

CHANGELOG.md
Sources/SwifterSwift/Resources/PrivacyInfo.xcprivacy

fixed: [1182](https://github.com/SwifterSwift/SwifterSwift/issues/1182)

Fixed: Missing an expected key: 'NSPrivacyCollectedDataTypes'

---

CHANGELOG.md
SwifterSwift.podspec
SwifterSwift.xcodeproj/project.pbxproj

🚀 
We need to release a new version so that any project including SwifterSwift can generate a privacy report, as mentioned in #1182.

Release 6.2.0

---

CHANGELOG.md
Sources/SwifterSwift/CoreAnimation/CATransform3DExtensions.swift

https://github.com/SwifterSwift/SwifterSwift/pull/1197 does not fix all Xcode 16 compilation errors. The library compiles when directly open in Xcode, but not when integrated through Cocoapods. This PR address this errors

Fixed additional compilation errors for Xcode 16

---

CHANGELOG.md
Examples/Examples.playground/Pages/02-FoundationExtensions.xcplaygroundpage/Contents.swift

- [ X] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ X] New extensions are written in Swift 5.6.
- [ X] New extensions support iOS 12.0+ / tvOS 12.0+ / macOS 10.13+ / watchOS 4.0+, or use `@available` if not.
- [ X] I have added tests for new extensions, and they passed.
- [ X] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ X] All extensions are declared as **public**.
- [ X] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

Fix error in Playground Foundation Example - import Foundation

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/ArrayExtensions.swift

initializedCount should be equal to the number of successfully initialized elements.

Update ArrayExtensions.swift 

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
Tests/SwiftStdlibTests/SequenceExtensionsTests.swift

- [ x] New extensions are written in Swift 5.6.
- [ x] New extensions support iOS 12.0+ / tvOS 12.0+ / macOS 10.13+ / watchOS 4.0+, or use `@available` if not.
- [ x] I have added tests for new extensions, and they passed.
- [ x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ x] All extensions are declared as **public**.
- [ x] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

Remove method that exists in stdlib

---

CHANGELOG.md
Sources/SwifterSwift/SwiftStdlib/FloatingPointExtensions.swift
Tests/SwiftStdlibTests/FloatingPointExtensionsTests.swift

🚀
Instead of using the Math functions (by importing Foundation) we can use `rounded(_:)`.

Calculate ceil and floor using built-in functions

---

CHANGELOG.md
Sources/SwifterSwift/UIKit/UIViewExtensions.swift
Tests/UIKitTests/UIViewExtensionsTests.swift

🚀 This PR adds a new extension to `UIView`:
- `separator(color:height:spacing:)` method, which makes it easy to add a bottom border/separator to any UIView.
- Fully tested with `XCTest` (`UIViewExtensionsTests`)
- `CHANGELOG.md` updated under `[Unreleased]`
```swift
let view = UIView()
view.separator(color: .gray, height: 1, spacing: 4)
```

Add UIView.separator extension with tests and changelog 🚀
