- SwifterSwift/SwifterSwift/Extensions/StringExtensions.swift
Added small function to return URL format which might be useful. thanks
```swift
let str = "http://www.google.com"
let url = str.toURL
```
> Added string extension to return URL type

- SwifterSwift/SwifterSwift/Extensions/IntExtensions.swift
- SwifterSwift/SwifterSwift/Extensions/UI/UIViewExtensions.swift
- [ x ] I checked the [**Contributing Guidelines**](https://github.com/omaralbeik/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ x ] New extensions support iOS 8 or later.
- [ x ] New extensions are written in Swift 3.
- [ x  ] New extensions were created in **development branch**.
- [ x ] Pull request was created to **development head branch**.
- [ x ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ x ] All comments headers have the word **SwifterSwift:** before description.
> Int & UIView extensions

- README.md
> Made some tiny changes.

- SwifterSwift/SwifterSwift/Extensions/UI/UIButtonExtensions.swift
Just an update to set properties by states
> Update uibutton setSomethingFor:State

- .github/PULL_REQUEST_TEMPLATE.md
> fix the typo

- Source/Extensions/StringExtensions.swift
- Tests/SwifterSwiftTests/StringExtensionsTests.swift
> String.count: fix and add test for capital letters with case insensitive

- SwifterSwift.podspec
- SwifterSwift.xcodeproj/project.pbxproj
- SwifterSwift.xcodeproj/xcshareddata/xcschemes/SwifterSwift macOS.xcscheme
Hello. Initial setup for macOS I did the same as previous ones. It does not build yet. Quite a lot of stuff depends on UIKit that is not available in macOS.
> [#87] intial macOS target setup

- Source/Extensions/SwifterSwift.swift
- Tests/SwifterSwiftTests/SwifterSwiftTests.swift
Two utility functions I keep using in my projects quite often. Hope you find them useful.
> Add debounce and delay utility functions

- .travis.yml
Should be fine now, but wait with merging for travis.
> fix xcpretty exit statuses config

- Source/Extensions/UI/UIColorExtensions.swift
- SwifterSwift.xcodeproj/project.pbxproj
- Tests/SwifterSwiftTests/UIColorExtensionsTests.swift
UIColorExtensions tests. Improvements related to the implementation itself, in order to pass tests.
> Add UIColorExtensions tests and fix issues in extension implementation

- Source/Extensions/CharacterExtensions.swift
- Tests/SwifterSwiftTests/CharacterExtensionsTests.swift
> Added isLower and isUpper to Character extensions

- Source/Extensions/UIKit/UICollectionViewExtensions.swift
- Source/Extensions/UIKit/UIStoryboardExtensions.swift
- Source/Extensions/UIKit/UITableViewExtensions.swift
- Tests/SwifterSwiftTests/CocoaExtensionsTests/CGFloatExtensionsTests.swift
- Adds 1 new extension to UIStoryboard
```swift 
public static var mainStoryboard: UIStoryboard?
```
- Fixes missing public keywords on ```reloadData``` method (UITableView/UICollectionView)
- Fixes wrong type constraint on `register<T: UICollectionViewCell>(cellWithClass:)`
- Adds a few tests to CGFloat extensions
> Add UIStoryboardExtension, update CGFloat tests, fix typos

- Source/Extensions/Cocoa/CGPointExtensions.swift
> Should be `-` here?

- Source/Extensions/ArrayExtensions.swift
- Tests/SwifterSwiftTests/ArrayExtensionsTests.swift
> Swap index position array extension.

- Source/Extensions/ArrayExtensions.swift
- Tests/SwifterSwiftTests/ArrayExtensionsTests.swift
> Convenience remove all passing an array of items to be removed.

- Source/Extensions/CharacterExtensions.swift
- Tests/SwifterSwiftTests/CharacterExtensionsTests.swift
> Few simple character extensions.

- Source/Extensions/ArrayExtensions.swift
- Source/Extensions/DateExtensions.swift
- Tests/SwifterSwiftTests/ArrayExtensionsTests.swift
- Tests/SwifterSwiftTests/DateExtensionsTests.swift
Add new **Array** extensions
`func forEach(where condition: (Element) -> Bool, body: (Element) -> Void)`
`func take(while condition: (Element) -> Bool) -> [Element] `
`func skip(while condition: (Element) -> Bool) -> [Element]`
`mutating func keep(while condition: (Element) -> Bool)`
`mutating func drop(while condition: (Element) -> Bool)`
Add new **Date** extensions
`isInWeekday`
> Add new Array & Date extensions

- README.md
> Added Slack badge

- Source/Extensions/DictionaryExtensions.swift
- Tests/SwifterSwiftTests/DictionaryExtensionsTests.swift
> Add dictionary new extensions and operators.

- Source/Extensions/ArrayExtensions.swift
- Source/Extensions/Cocoa/NSColorExtensions.swift
- Source/Extensions/Cocoa/NSViewExtensions.swift
- Source/Extensions/CollectionExtensions.swift
- Source/Extensions/DictionaryExtensions.swift
- Source/Extensions/DoubleExtensions.swift
- Source/Extensions/FloatExtensions.swift
- Source/Extensions/IntExtensions.swift
- Source/Extensions/LocaleExtensions.swift
- Source/Extensions/StringExtensions.swift
- Source/Extensions/UIKit/UIBarButtonItemExtensions.swift
- Source/Extensions/UIKit/UICollectionViewExtensions.swift
- Source/Extensions/UIKit/UIColorExtensions.swift
- Source/Extensions/UIKit/UINavigationBarExtensions.swift
- Source/Extensions/UIKit/UINavigationControllerExtensions.swift
- Source/Extensions/UIKit/UITableViewExtensions.swift
- Source/Extensions/UIKit/UIViewExtensions.swift
- Tests/SwifterSwiftTests/DictionaryExtensionsTests.swift
- Tests/SwifterSwiftTests/UIKitExtensionsTests/UIBarButtonExtensionsTests.swift
- Tests/SwifterSwiftTests/UIKitExtensionsTests/UINavigationControllerExtensionsTests.swift
- Fixed doc headers to match Xcode header template.
- Updated some methods arguments based on Swift 3 API guidelines.
> Updated doc headers

- Source/Extensions/ArrayExtensions.swift
- Tests/SwifterSwiftTests/ArrayExtensionsTests.swift
> Filtered map array extension.

- Source/Extensions/ArrayExtensions.swift
> Throwable closures signatures on array extensions.

- Source/Extensions/DataExtensions.swift
- Source/Extensions/DictionaryExtensions.swift
- Tests/SwifterSwiftTests/DataExtensionsTests.swift
> Byte array from data extension.

- Source/Extensions/StringExtensions.swift
- Tests/SwifterSwiftTests/StringExtensionsTests.swift
> isValidFileUrl string extension

- Source/Extensions/ArrayExtensions.swift
- Tests/SwifterSwiftTests/ArrayExtensionsTests.swift
> groupBy array extension

- Source/Extensions/ArrayExtensions.swift
> improving group array extension implementation.

- README.md
Some minor changes to the README
> harmonized README.md examples

- Tests/SwifterSwiftTests/UIKitExtensionsTests/UINavigationControllerExtensionsTests.swift
- Tests/SwifterSwiftTests/UIKitExtensionsTests/UISliderExtensionsTests.swift
- Tests/SwifterSwiftTests/UIKitExtensionsTests/UITableViewExtensionsTests.swift
> fixing async tests that was causing crash.

- Source/Extensions/ArrayExtensions.swift
- Tests/SwifterSwiftTests/ArrayExtensionsTests.swift
> For each slice implementation.

- CHANGELOG.md
Updates missing CHANGELOG.md entries for #193 & #194
> Update CHANGELOG.md missing entries

- Source/Extensions/StringExtensions.swift
- Tests/SwifterSwiftTests/StringExtensionsTests.swift
> Adds string has unique characters method

- Sources/Extensions/UIKit/UITextFieldExtensions.swift
- Tests/UIKitTests/UITextFieldExtensionsTests.swift
> add left icon in textfield

- Sources/Extensions/Cocoa/CGPointExtensions.swift
- Sources/Extensions/Cocoa/CGSizeExtensions.swift
- Sources/Extensions/Foundation/ArrayExtensions.swift
> Adding some missing docs exemples.

- SwifterSwift.podspec
Added module_name to podspecs file, hopefully this will help solving conflicts with other 3rd party libraries
> Fixes #201

- Sources/Extensions/Foundation/IntExtensions.swift
- Tests/FoundationTests/IntExtensionsTests.swift
**mostly :)**
**of course!**
**foundation extension**
**yes, except mac, i have 10.11, whereas it complained about 10.12+ sdk**
**also explained speedy stuff**
**since copied from another ;)**
> Ref: #221
> Fixes #221

- Tests/UIKitTests/UISliderExtensionsTests.swift
> Fixed unit test of uislider #209

- CHANGELOG.md
- Sources/Extensions/Foundation/DateExtensions.swift
- Tests/FoundationTests/DateExtensionsTests.swift
- adds `isInThisWeek`, `isInThisMonth`, `isInThisYear` extensions to `Date`
**TODO:**
> Add Date extensions isInThisWeek, isInThisMonth, isInThisYear

- .travis.yml
- Dangerfile
- Gemfile
If I set this up properly we should see a message from @SwifterSwiftBot. I accidently left an ugly commit so we'll have to squash that
> [Added] Danger to continuous integration

- CHANGELOG.md
- Sources/Extensions/Shared/ColorExtensions.swift
- Sources/Extensions/UIKit/UIColorExtensions.swift
- SwifterSwift.xcodeproj/project.pbxproj
- Tests/UIKitTests/UIColorExtensionsTests.swift
- Move `blend` from UIColor to Color
- Add `cgFloatComponents`
- Correct a typo in `rgbComponenets`
> Move blend from UIColor to Color

- CHANGELOG.md
- README.md
> Fixed wording in 2 of the files (Readme, Changelog)

- README.md
Thanks to @plbrooks for reporting
> Fix typo in website name

- .travis.yml
- Dangerfile
> Added calls to swiftlint and pod lib lint in Travis

- README.md
> Update slack badge

- Sources/Extensions/Foundation/DateExtensions.swift
- Tests/FoundationTests/DateExtensionsTests.swift
> Closes #298 Date.year not working properly

- Sources/Extensions/Foundation/CalendarExtensions.swift
- SwifterSwift.xcodeproj/project.pbxproj
- Tests/FoundationTests/CalendarExtensionTest.swift
- [ x ] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ x ] New extensions are written in Swift 4.
- [ x ] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [ x ] I have added tests for new extensions, and they passed.
- [ x ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ x ] All extensions are declared as **public**.
> Added extension for Number of days in a month.

- .travis.yml
> #312 Update travis to use xcode 9.1

- CHANGELOG.md
- README.md
- Sources/Extensions/SwiftStdlib/StringExtensions.swift
- Sources/Extensions/UIKit/UIDatePickerExtensions.swift
- SwifterSwift.xcodeproj/project.pbxproj
- Tests/SwiftStdlibTests/StringExtensionsTests.swift
- Tests/UIKitTests/UIDatePickerExtensionsTests.swift
> New extensions

- Tests/FoundationTests/DateExtensionsTests.swift
I shut down some annoying linting warnings!
> fixed SwiftLint warnings in date tests

- CHANGELOG.md
- Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
- Tests/SwiftStdlibTests/ArrayExtensionsTests.swift
> Adding sorted by keyPath array methods.

- LICENSE
> Update copyright date to 2018

- Sources/Extensions/UIKit/UIViewExtensions.swift
> Fix React-Native conflict issue

- CHANGELOG.md
- Sources/Extensions/UIKit/UIViewControllerExtensions.swift
- Tests/UIKitTests/UIViewControllerExtensionsTests.swift
> Added helper method for conveniently displaying an alert from any view controller

- CHANGELOG.md
- Sources/Extensions/UIKit/UICollectionViewExtensions.swift
- Sources/Extensions/UIKit/UITableViewExtensions.swift
- SwifterSwift.xcodeproj/project.pbxproj
- Tests/Resources/UICollectionViewCell.xib
- Tests/UIKitTests/UICollectionViewExtensionsTests.swift
- Tests/UIKitTests/UITableViewExtensionsTests.swift
> UITableView and UICollectionView extensions

- Dangerfile
> Fixing danger Test files changes check inverted logic.

- README.md
> LICENSE section on Readme

- CONTRIBUTING.md
Update Contributing to containing the one to one relation between extension and test file and added some note that every extension should be tested.
Should resolve #389
> Update Contributing to containing the one to one relation information

- CHANGELOG.md
> Update CHANGELOG to fix incorrectly placed PR #363

- CHANGELOG.md
- README.md
- Sources/Extensions/SwiftStdlib/CollectionExtensions.swift
- Tests/SwiftStdlibTests/ArrayExtensionsTests.swift
- Tests/SwiftStdlibTests/CollectionExtensionsTests.swift
> Fix random item

- CHANGELOG.md
- Sources/Extensions/SwiftStdlib/OptionalExtensions.swift
- Tests/SwiftStdlibTests/OptionalExtensionsTests.swift
I am pretty sure I am not implementing a duplicate method this time 😂.
> Created Optional.unwrapped(or:Error) Method

- CHANGELOG.md
- Sources/Extensions/UIKit/UIViewExtensions.swift
> Fix UIView.addShadow extension.

- CHANGELOG.md
- Sources/Extensions/SwiftStdlib/StringExtensions.swift
- Tests/SwiftStdlibTests/StringExtensionsTests.swift
Added new methods and var to String Extensions:
- public var isSpelledCorrectly: Bool
- func deletingPrefix()
- func deletingSuffix()
> String extensions

- CHANGELOG.md
- Sources/Extensions/SwiftStdlib/Deprecated/SwiftStdlibDeprecated.swift
- Sources/Extensions/SwiftStdlib/SequenceExtensions.swift
- SwifterSwift.xcodeproj/project.pbxproj
- Tests/SwiftStdlibTests/SequenceExtensionsTests.swift
> Add SwiftLint to test targets

- .travis.yml
Let's see this  
https://blog.travis-ci.com/2018-04-09-say-bonjour-to-xcode-93-and-macos-high-sierra
> updating travis osximage

- CHANGELOG.md
- Sources/Extensions/Foundation/URLExtensions.swift
- Tests/FoundationTests/URLExtensionsTests.swift
> Adding delete all path components URL extensions.

- .travis.yml
- CHANGELOG.md
- Sources/Extensions/SwiftStdlib/CharacterExtensions.swift
- Tests/SwiftStdlibTests/CharacterExtensionsTests.swift
> 🚀 Add random method to Character

- CHANGELOG.md
- README.md
Resolves #492
Wasn't 100% sure where to add changes to the docs in the CHANGELOG. I see that most have been under an enhancements section, but that didn't seem fitting. Put it in the "Added" section since it was added. Happy to change if there's a better place for it.
> Add SpriteKit to README

- CHANGELOG.md
- Sources/Extensions/SwiftStdlib/SequenceExtensions.swift
- Tests/SwiftStdlibTests/SequenceExtensionsTests.swift
> Add containsDuplicates to check whether a collection contains duplicates

- Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
- Tests/SwiftStdlibTests/ArrayExtensionsTests.swift
This PR introduces `removeElement(_ element:)`, which removes first instance of an element from array. 🎉
> create removeElement(_) in Array extension.

- Sources/Extensions/Foundation/DateExtensions.swift
- Sources/Extensions/Shared/ColorExtensions.swift
- Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
- Sources/Extensions/SwiftStdlib/Deprecated/SwiftStdlibDeprecated.swift
- Sources/Extensions/SwiftStdlib/SignedIntegerExtensions.swift
- Sources/Extensions/SwiftStdlib/SignedNumericExtensions.swift
- Sources/Extensions/UIKit/UITextFieldExtensions.swift
- Sources/Extensions/UIKit/UIViewExtensions.swift
> Complete jazzy docs to 100%

- CHANGELOG.md
- Sources/Extensions/SwifterSwift.swift
- Sources/Extensions/UIKit/UIStackViewExtensions.swift
- Tests/SwifterSwiftTests.swift
- Tests/UIKitTests/UIStackViewExtensionsTest.swift
Add `addArrangedSubviews(_ views: [UIView])` and `removeArrangedSubviews()` extensions to `UIStackView`.
> Closes #474

- Sources/Extensions/CoreGraphics/CGFloatExtensions.swift
- Sources/Extensions/UIKit/UINavigationControllerExtensions.swift
- Sources/Extensions/UIKit/UISearchBarExtensions.swift
- Sources/Extensions/UIKit/UIViewExtensions.swift
- SwifterSwift.xcodeproj/project.pbxproj
- Tests/FoundationTests/FileManagerExtensionsTests.swift
- Tests/FoundationTests/NSAttributedStringExtensionsTests.swift
- Tests/SharedTests/ColorExtensionsTests.swift
- Tests/SwiftStdlibTests/CollectionExtensionsTests.swift
- Tests/SwifterSwiftTests.swift
- Tests/UIKitTests/UIAlertControllerExtensionsTests.swift
- Tests/UIKitTests/UICollectionViewExtensionsTests.swift
- Tests/UIKitTests/UIEdgeInsetsExtensionsTests.swift
- Tests/UIKitTests/UINavigationControllerExtensionsTests.swift
- Tests/UIKitTests/UIViewExtensionsTests.swift
Add new tests and increase test coverage before the next release.
> Add new tests

- Sources/Extensions/SwiftStdlib/ArrayExtensions.swift
- Sources/Extensions/SwiftStdlib/IntExtensions.swift
- Sources/Extensions/SwiftStdlib/StringExtensions.swift
> Fix docs of ArrayExtensions and StringExtensions.

- Dangerfile
Just putting labels test summaries on xcode-summary :))
> Label the xcode summary with the platform.

- CONTRIBUTING.md
Separated rules about adding tests in a dedicated section.  Fixes #588 🚀 
- [ x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
> Updating CONTRIBUTING.md for Adding Test.

- CHANGELOG.md
- Sources/Extensions/UIKit/UIViewExtensions.swift
- Tests/UIKitTests/UIViewExtensionsTests.swift
> UIView: add and remove multiple gesture recognizers at once with array of UIGestureRecognizer

- CHANGELOG.md
> Fixing changelog entries.

- CHANGELOG.md
- Sources/Extensions/Foundation/URLExtensions.swift
- Tests/FoundationTests/URLExtensionsTests.swift
Resolves: #464
I'm happy to make adjustments if required.
> Adds new method on URL called droppedScheme

- CHANGELOG.md
- Sources/Extensions/CoreGraphics/CGSizeExtensions.swift
- Tests/CoreGraphicsTests/CGSizeExtensionsTests.swift
> Add operators for CGSize

- CHANGELOG.md
- Sources/Extensions/SwiftStdlib/StringExtensions.swift
> Fix unicodeArray

- CHANGELOG.md
- Sources/Extensions/UIKit/UIImageExtensions.swift
> Fixed image cropped method

- Sources/Extensions/SwiftStdlib/DictionaryExtensions.swift
- Sources/Extensions/SwiftStdlib/RangeReplaceableCollectionExtensions.swift
- Sources/Extensions/SwiftStdlib/StringExtensions.swift
- Sources/Info.plist
🚀
This is more of a maintenance PR than anything. Just wanted to do some cleaning of usage of the random values/elements. I think this is a bit cleaner (and probably more performant in the case of the random strings).
I also updated the version just so that it points to the current version (it should be 1 ahead of the latest tag, right?).
> (Maintenance) Random values

- CONTRIBUTING.md
> Update CONTRIBUTING.md to mention adding a subspec for new modules

- .travis.yml
> Only triggering push builds for master.

- .travis.yml
> Updating travis script

- Sources/SwifterSwift/UIKit/UIEdgeInsetsExtensions.swift
Resolved an issue where extension methods were internal instead of public.
> Resolve Issue #651

- CHANGELOG.md
- Sources/SwifterSwift/CoreGraphics/CGSizeExtensions.swift
- Tests/CoreGraphicsTests/CGSizeExtensionsTests.swift
- [/] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [/] New extensions are written in Swift 4.
- [/] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [/] I have added tests for new extensions, and they passed.
- [/] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [/] All extensions are declared as **public**.
- [/] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.
> Add aspectRatio and max properties to CGSize

- Gemfile.lock
> Updating bundle to fix vulnerability issue

- README.md
> remove duplicate optional link

- CHANGELOG.md
- Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
> ♻️ Refactor sum() to make it more Swift-er

- Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
> 💡 Documenting String appendingPathComponent

- CHANGELOG.md
- Sources/SwifterSwift/UIKit/UIImageExtensions.swift
- Tests/UIKitTests/UIImageExtensionsTests.swift
> Update to UIImage extensions and new init 🚀 

- .swiftlint.yml
- .travis.yml
- Sources/SwifterSwift/UIKit/UIImageExtensions.swift
> Fixing swiftlint on travis failing on travis

- CHANGELOG.md
- README.md
- Sources/SwifterSwift/CoreLocation/CLVisitExtensions.swift
- SwifterSwift.xcodeproj/project.pbxproj
- Tests/CoreLocationTests/CLVisitExtensionsTests.swift
> added initial clvisit extension with location property

- Package.swift
- Sources/SwifterSwift/CoreLocation/CLLocationArrayExtensions.swift
- Sources/SwifterSwift/Foundation/FileManagerExtensions.swift
- Sources/SwifterSwift/SceneKit/SCNCapsuleExtensions.swift
- Sources/SwifterSwift/SceneKit/SCNConeExtensions.swift
- Sources/SwifterSwift/SceneKit/SCNShapeExtensions.swift
- Sources/SwifterSwift/UIKit/UIImageExtensions.swift
- Sources/SwifterSwift/UIKit/UIViewExtensions.swift
- SwifterSwift.xcodeproj/project.pbxproj
- Tests/AppKitTests/NSImageExtensionsTests.swift
- Tests/CoreLocationTests/CLLocationArrayExtensionsTests.swift
- Tests/FoundationTests/DateExtensionsTests.swift
- Tests/SceneKitTests/SCNShapeExtensionsTests.swift
- Tests/UIKitTests/UIBezierPathExtensionsTests.swift
- Tests/UIKitTests/UIImageExtensionsTests.swift
- Tests/UIKitTests/UIRefreshControlExntesionsTests.swift
- Tests/UIKitTests/UISearchBarExtensionsTests.swift
- Tests/UIKitTests/UITextViewExtensionsTests.swift
At first I was trying to get the tests to run when opening the project as a Swift package in Xcode, but apparently unit tests don't find any resources in that state so doesn't work.
Nevertheless, I cleaned up some things and thought they should be merged in.
> Project clean

- README.md
This is to thank you Guy for the work you've been doing in this project.
Thank you for all the great work you've been doing to help with maintaining this project \o/ 
We really appreciate it 💯 
cc @guykogus
> Special Thanks Update

- .github/workflows/CI.yml
- Package.swift
> [CI] Update to XCode 11.4 and tools to 5.2

- CHANGELOG.md
- Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
- Tests/SwiftStdlibTests/StringExtensionsTests.swift
fixed Fatal error: Can't form Range with upperBound < lowerBound
> fixed "".truncated crashed

- CHANGELOG.md
- README.md
- Sources/SwifterSwift/HealthKit/HKActivitySummaryExtensions.swift
- SwifterSwift.podspec
- SwifterSwift.xcodeproj/project.pbxproj
- Tests/HealthKitTests/HKActivitySummaryExtensionsTests.swift
> Added HKActivitySummary extensions

- CHANGELOG.md
- Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift
- Tests/SwiftStdlibTests/StringExtensionsTests.swift
Returns an escaped string for inclusion in a regex pattern. See #879
> added String.regexEscaped

- CHANGELOG.md
- Sources/SwifterSwift/UIKit/UIViewExtensions.swift
- SwifterSwift.xcodeproj/project.pbxproj
- Tests/ResourcesTests/UIImageView.xib
- Tests/ResourcesTests/tvOS/UIImageView.xib
- Tests/UIKitTests/UIViewExtensionsTests.swift
Loads a UIView of a particular type from a nib file. See #879.
> loadFromNib(withClass)

- .github/workflows/CI.yml
- Brewfile
- Brewfile.lock.json
- Sources/SwifterSwift/UIKit/UIDatePickerExtensions.swift
> Fix swiftlint error

- .github/workflows/CI.yml
- Brewfile.lock.json
> [CI] Updating brew version

- Sources/SwifterSwift/UIKit/UIViewExtensions.swift
> Update effectiveUserInterfaceLayoutDirection API availability

- Sources/SwifterSwift/CoreGraphics/CGPointExtensions.swift
- Sources/SwifterSwift/CoreGraphics/CGVectorExtensions.swift
- Sources/SwifterSwift/SceneKit/SCNVector3Extensions.swift
- Sources/SwifterSwift/SwiftStdlib/DictionaryExtensions.swift
> [NFC] Fixing shorthand swiftlint warnigs

- Brewfile
- Brewfile.lock.json
> [CI] Fixing brew version

- README.md
Fix broken Slack badge in read me page
> Fix Slack badge

- Sources/SwifterSwift/Foundation/DateExtensions.swift
> Modify error comments

- CHANGELOG.md
- Sources/SwifterSwift/Foundation/NSAttributedStringExtensions.swift
- Tests/FoundationTests/NSAttributedStringExtensionsTests.swift
Hello.
This pull request fixes #984.
> Add joined(separator:)

- README_CN.md
Add Chinese language document（`README_CN.md`）
> Add README Chinese document.

- CHANGELOG.md
- Sources/SwifterSwift/UIKit/UIButtonExtensions.swift
- Tests/UIKitTests/UIButtonExtensionsTests.swift
This PR is referenced on #1037 .
> Feature set background color for state in UIButton

- CHANGELOG.md
In my last merged [PR](https://github.com/SwifterSwift/SwifterSwift/pull/1045) I forgot to push updated changelog. This PR fixes that.
> Added missing changelog for PR #1045

- README_CN.md
> Update README_CN.md 🚀

- Sources/SwifterSwift/SwiftStdlib/Deprecated/StdlibDeprecated.swift
- Sources/SwifterSwift/SwiftStdlib/SequenceExtensions.swift
> Fix swiftlint warnings

- CHANGELOG.md
- Sources/SwifterSwift/UIKit/UIButtonExtensions.swift
- Tests/UIKitTests/UIButtonExtensionsTests.swift
🚀
Hello.
Add methods for focused state.
> Focused state

- Sources/SwifterSwift/SwiftStdlib/CollectionExtensions.swift
> chore: Lint and Fix Description of `Collection.adjacentPairs()`

- Sources/SwifterSwift/UIKit/UIViewExtensions.swift
Replaced the for-each constraints activation with `NSLayoutConstraint.activate` within `anchor` function of UIView extension.
If we are creating constraints programmatically, using the `activate` method of `NSLayoutConstraint` can improve performance by activating all the constraints at once, rather than activating them one by one. I believe this also improves code readability. 
I ran the existing test `testAnchor` for testing the `anchor` function of UIView available in `UIViewExtensionsTests.swift` file. It passed. 
As a new contributor to open source, this is my first ever contribution to any project. I would greatly appreciate advice and feedback from the experienced community here to help improve my work.
> Replaced the for-each constraints activation with `NSLayoutConstraint` 🚀 

- Sources/SwifterSwift/Foundation/DateExtensions.swift
> Make Date.weekday documentation clearer

- SwifterSwift.xcodeproj/project.pbxproj
> Run SwiftFormat and SwiftLint at the start of each build phase

- README.md
- README_CN.md
Update some information for v6.0.0 release.
However, I'm not sure should the badge of Xcode should be updated too. Can any one verify it?
> Update README.md for v6.0.0 Release

- CHANGELOG.md
- README.md
- README_CN.md
- Sources/SwifterSwift/Foundation/MeasurementExtensions.swift
- Tests/FoundationTests/MeasurementExtensionsTests.swift
> Measurement +=, -=, *=, /=

- CHANGELOG.md
- SwifterSwift.podspec
- SwifterSwift.xcodeproj/project.pbxproj
🚀
We need to release a new version ASAP because of #1175. It can affect people releasing new apps in the next 2 months.
> Release 6.1.0

- CHANGELOG.md
- SwifterSwift.podspec
- SwifterSwift.xcodeproj/project.pbxproj
🚀
I forgot to add the privacy manifest to the podspec file.
> Release 6.1.1

- Tests/FoundationTests/URLExtensionsTests.swift
> Fix testDropScheme for Android
